- id: update_notifications
  alias: Update notifications
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.slack
    data:
      message: 'There is a new Home Assistant release available.'

- id: startup_notification
  alias: Start Up
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: notify.default_group
      data:
        message: ":white_check_mark: Home Assistant is now Running.\n@bishop is online. :robot_face:"
        target: [
          "448389226078273537"
        ]
        
- id: new_device_on_network
  alias: New Device On Network
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    - service: notify.slack
      data_template: 
        message: ':warning: New device discovered on network at {{now()}}'

