# - id: update_notifications
#   alias: Update notifications
#   trigger:
#     platform: state
#     entity_id: updater.updater
#   action:
#     service: notify.slack
#     data:
#       message: There is a new Home Assistant release available.
- id: startup_notification
  alias: Start Up
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: notify.default_group
    data:
      message: ':white_check_mark: Home Assistant is now Running.

        @bishop is online. :robot_face:'
      target:
      - '448389226078273537'
- id: new_device_on_network
  alias: New Device On Network
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
  - service: notify.slack
    data_template:
      message: ':warning: New device discovered on network at {{now()}}'
- id: '1638819604857'
  alias: Office Lights on Motion
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 15bd8e0df94480efdb1ca049a477eb0e
    entity_id: binary_sensor.4_in_1_sensor_home_security_motion_detection
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 0
  condition:
  - type: is_illuminance
    condition: device
    device_id: 15bd8e0df94480efdb1ca049a477eb0e
    entity_id: sensor.4_in_1_sensor_illuminance
    domain: sensor
    below: 50
  action:
  - service: light.turn_on
    target:
      device_id:
      - b2fb2be005fea7448966c5527eb96267
      - cc898b4d6eeadb4f276afcab001b584d
  mode: single
- id: '1638930339111'
  alias: Turn on Patio Lights Wireless Switch
  description: ''
  trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: 0ec462247667f81f26301c4bbde91060
      label: Scene 001
      value: KeyPressed
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.multirelay
  mode: single
- id: '1638930579684'
  alias: Turn off patio lights wireless switch
  description: ''
  trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: 0ec462247667f81f26301c4bbde91060
      label: Scene 002
      value: KeyPressed
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.multirelay
  mode: single
- id: '1639085432071'
  alias: Motion-activated Light
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.4_in_1_sensor_home_security_motion_detection
      light_target:
        entity_id:
        - light.office_left
        - light.office_right
      no_motion_wait: 300
- id: '1639152671247'
  alias: Front Porch Motion
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: a184662d302d4389e382e555f33e47a5
    entity_id: binary_sensor.000_motion_alarm
    domain: binary_sensor
  condition: []
  action:
  - device_id: 6fe50131167e2a85a6886673c2b026e3
    domain: select
    entity_id: select.wled_preset
    type: select_option
    option: Doorbell
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - device_id: 6fe50131167e2a85a6886673c2b026e3
    domain: select
    entity_id: select.wled_preset
    type: select_option
    option: Nightlight
  mode: single
- id: '1643386656949'
  alias: Alert when people are moving
  description: ''
  trigger:
  - platform: state
    entity_id: person.aiden
  condition: []
  action:
  - service: notify.mobile_app_mick_phone
    data:
      message: Aiden is {{ states('person.aiden') }}
  mode: single
- id: '1645651094797'
  alias: Porch lights At Night
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '0'
  condition: []
  action:
  - type: turn_on
    device_id: 5a7435e0f1a5bbd910259910b4545f69
    entity_id: switch.in_wall_switch_on_off
    domain: switch
  mode: single
- id: '1645651466135'
  alias: Porch Lights at Dawn
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: '-1'
  condition:
  - condition: device
    type: is_on
    device_id: 5a7435e0f1a5bbd910259910b4545f69
    entity_id: switch.in_wall_switch_on_off
    domain: switch
  action:
  - type: turn_off
    device_id: 5a7435e0f1a5bbd910259910b4545f69
    entity_id: switch.in_wall_switch_on_off
    domain: switch
  mode: single
- id: '1645657637978'
  alias: Home Assistant Update Notification for Android
  description: ''
  use_blueprint:
    path: fortepc/update-notif-for-android.yaml
    input:
      clickAction: https://my.home-assistant.io/redirect/supervisor/
      delay: 0
      notify_device: d44a65e14b193afb2db47daf3b963b5d
- id: '1647213983200'
  alias: Turn on Family Room Lights
  description: ''
  trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: e2944ecc71dba5d94ba234950d8d1db8
      label: Scene 004
      value: 0
  condition: []
  action:
  - type: toggle
    device_id: 3bef8ebed1eacf0854c67519d82d70e9
    entity_id: light.family_room_left
    domain: light
  - type: toggle
    device_id: cb91cae3981f7aa59b55f8c2c66f3a36
    entity_id: light.family_room_right
    domain: light
  - type: toggle
    device_id: c855cdf9937247a2015eecf94d6419a9
    entity_id: light.family_room_middle
    domain: light
  mode: single
- id: '1647214590168'
  alias: Toggle Deck Lights Wired Switch
  description: ''
  trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: e2944ecc71dba5d94ba234950d8d1db8
      label: Scene 001
      value: 0
  condition: []
  action:
  - service: switch.toggle
    data: {}
    target:
      entity_id: switch.multirelay
  mode: single
