- alias: Michael's Presence
  trigger:
    platform: state
    entity_id: device_tracker.goibniu_goibniu
  action:
    service: notify.wb_slack
    data:
      message: ':house: Michael is {{ states("device_tracker.goibniu_goibniu") }}'
- alias: Update notifications
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.wb_slack
    data:
      message: 'There is a new Home Assistant release available.'
- alias: Garage Door
  trigger:
    platform: state
    entity_id: cover.garage_door
  action:
    - service: notify.wb_slack
      data_template:
        message: ':parking: The garage door is {{ trigger.to_state.state }}'
    - service: shell_command.set_master_garage_state
- alias: Start Up
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: notify.wb_slack
      data:
        message: ":white_check_mark: Home Assistant is now Running.\n@bishop is online. :robot_face:"
- alias: Front Porch Motion
  trigger: 
    platform: state
    entity_id: sensor.frontporchnorth_events
  condition:
    condition: template
    value_template: '{{ trigger.from_state.state < trigger.to_state.state }}'
  action:
    - service: shell_command.get_latest_zm_event
- alias: Front Door Motion
  trigger: 
    platform: state
    entity_id: sensor.fand_events
  action:
    - service: notify.wb_slack
      data_template: 
        message: ':door: New motion event at Front Door (From {{ trigger.from_state.state }} to {{ trigger.to_state.state }}'
- alias: Lights Out At Midnight
  trigger:
    platform: time
    after: '00:00:00'
  action:
    service: light.turn_off
- alias: Game Mood Lighting
  trigger:
    platform: state
    entity_id: sensor.steam_76561197993153035
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ states.sensor.steam_76561197993153035.attributes.Game != "None"}}'
      - condition: template
        value_template: '{{ states.light.office_floor_lamp.state != "off"}}'
    action:
      service: light.turn_on
      entity_id: light.office_floor_lamp
      data:
        brightness: 75
- alias: Restore Office Lighting
  trigger:
    platform: state
    entity_id: sensor.steam_76561197993153035
    value_template: '{{ state.attributes.Game }}'
    to: 'None'
  action:
    service: light.turn_on
    entity_id: light.office_floor_lamp
    data:
      brightness: 75