- id: presence_michael
  alias: Michael's Presence
  trigger:
    platform: state
    entity_id: device_tracker.goibniu_goibniu
  action:
    service: notify.slack
    data:
      message: ':house: Michael is {{ states("device_tracker.goibniu_goibniu") }}'
- id: presence_mary
  alias: Mary's Presence
  trigger:
    platform: state
    entity_id: device_tracker.android1b27fe99b8b39bc3
  action:
    service: notify.slack
    data:
      message: ':house: Mary is {{ states("device_tracker.android1b27fe99b8b39bc3") }}'
- id: presence_people
  alias: Presence
  trigger:
    platform: state
    entity_id: group.people
  action:
    service: notify.slack
    data:
      message: ':house: Someone is {{ states("group.people") }}'
- id: update_notifications
  alias: Update notifications
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.slack
    data:
      message: 'There is a new Home Assistant release available.'
- id: garage_door_notification
  alias: Garage Door
  trigger:
    platform: state
    entity_id: cover.garage_door
  action:
    - service: notify.slack
      data_template:
        message: ':parking: The garage door is {{ trigger.to_state.state }}'
    - service: shell_command.set_master_garage_state
- id: startup_notification
  alias: Start Up
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: notify.slack
      data:
        message: ":white_check_mark: Home Assistant is now Running.\n@bishop is online. :robot_face:"
- id: front_porch_motion_notifications
  alias: Front Porch Motion
  trigger: 
    platform: state
    entity_id: sensor.frontporchnorth_events
  condition:
    condition: template
    value_template: '{{ trigger.from_state.state < trigger.to_state.state }}'
  action:
    - service: shell_command.get_latest_zm_event
- id: front_door_motion_notification
  alias: Front Door Motion
  trigger: 
    platform: state
    entity_id: sensor.fand_events
  action:
    - service: notify.slack
      data_template: 
        message: ':door: New motion event at Front Door (From {{ trigger.from_state.state }} to {{ trigger.to_state.state }}'
- id: lights_off_midnight
  alias: Lights Out At Midnight
  trigger:
    platform: time
    at: '00:00:00'
  action:
    service: light.turn_off
- id: game_mood_lighting
  alias: Game Mood Lighting
  trigger:
    platform: state
    entity_id: sensor.steam_76561197993153035
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ states.sensor.steam_76561197993153035.attributes.Game != "None"}}'
      - condition: template
        value_template: '{{ states.light.office_floor_lamp.state != "off"}}'
  action:
    service: light.turn_on
    entity_id: light.office_floor_lamp
    data:
      brightness: 75
- id: restore_office_lighting
  alias: Restore Office Lighting
  trigger:
    platform: template
    value_template: '{{ states.sensor.steam_76561197993153035.attributes.Game == "None" }}'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ states.light.office_floor_lamp.state != "off"}}'
      - condition: template
        value_template: '{{ states.light.office_floor_lamp.attributes.brightness <= 150}}'
  action:
    service: light.turn_on
    entity_id: light.office_floor_lamp
    data:
      brightness: 175
- id: kids_lights_bedtime
  alias: Kids Bed Time
  trigger:
    platform: time
    at: '18:45:00'
  action:
    service: light.turn_on
    entity_id: light.kids_rooms
    data:
      brightness: 75
- id: michaels_side_light_temp_night
  alias: Michaels Night Light Temp
  trigger:
    platform: state
    entity_id: light.michaels_side
    to: 'on'
  condition:
    condition: time
    after: '17:00:00'
  action:
    - service: light.turn_on
      entity_id: light.michaels_side
      data:
        brightness_pct: 50
        kelvin: 2200
    - service: notify.slack
      data_template: 
        message: ':bulb: Michaels Side Night (From {{ trigger.from_state.state }} to {{ trigger.to_state.state }})'
- id: michaels_side_light_temp_morning
  alias: Michaels Morning Light Temp
  trigger:
    platform: state
    entity_id: light.michaels_side
    to: 'on'
  condition:
    condition: time
    after: '06:00:00'
    before: '11:00:00'
  action:
    - service: light.turn_on
      entity_id: light.michaels_side
      data:
        brightness_pct: 60
        kelvin: 2700
    - service: notify.slack
      data_template: 
        message: ':bulb: Michaels Side Morning (From {{ trigger.from_state.state }} to {{ trigger.to_state.state }})'
- id: michaels_side_light_temp_day
  alias: Michaels Day Light Temp
  trigger:
    platform: state
    entity_id: light.michaels_side
    to: 'on'
  condition:
    condition: time
    after: '11:00:00'
    before: '17:00:00'
  action:
    - service: light.turn_on
      entity_id: light.michaels_side
      data:
        brightness_pct: 80
        kelvin: 4000
    - service: notify.slack
      data_template: 
        message: ':bulb: Michaels Side Day (From {{ trigger.from_state.state }} to {{ trigger.to_state.state }})'
- id: ui_day_mode
  alias: 'Set light theme for the day'
  initial_state: True
  trigger:
    - platform: sun
      event: 'sunrise'
  action:
    - service: frontend.set_theme
      data:
        name: default
- id: ui_night_mode
  alias: 'Set dark theme for the night'
  initial_state: True
  trigger:
    - platform: sun
      event: 'sunset'
  action:
    - service: frontend.set_theme
      data:
        name: darkred
- id: office_light_on_at_dusk
  alias: 'Turn on the office light at dusk'
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:00:00'
  condition:
    - condition: state
      entity_id: light.office
      state: 'off'
    - condition: state
      entity_id: sensor.camulos
      state: 'Online'
  action:
    service: light.turn_on
    entity_id: light.office