homeassistant:
  # Name of the location where Home Assistant is running
  name: Conways
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 1276
  # C for Celcius, F for Fahrenheit
  unit_system: imperial 
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

http:
  api_password: !secret api_password

media_player:
  platform: plex

camera:
    platform: rpi_camera
    name: Raspberry Pi Camera
    image_width: 640
    image_height: 480
    image_quality: 7
    image_rotation: 0
    timelapse: 1000
    horizontal_flip: 0
    vertical_flip: 0
    file_path: /tmp/image.jpg

climate:
  platform: radiotherm
  host: 
    - ***REMOVED***
  hold_temp: False

device_tracker:
  - platform: asuswrt
    host: ***REMOVED***
    username: !secret asus_username
    password: !secret asus_password
    protocol: telnet
  - platform: owntracks

mqtt:
  broker: ***REMOVED***
  port: 1883
  client_id: ha-fand
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

mqtt_eventstream:
  publish_topic: home/master
  subscribe_topic: home/slave

notify:
  name: wb_slack
  platform: slack
  api_key: !secret slack_api_key
  default_channel: '#home-automation'

rest_command:
  garage_icon:
    url: 'http://***REMOVED***:8123/api/states/group.garagetab'
    method: post
    payload: '{"attributes": {"entity_id": ["cover.garage_door", "media_player.roku_2_xd__12g2d0036416"], "friendly_name": "Garage", "hidden": true, "icon": "mdi:garage-open", "order": 3, "view": true}, "entity_id": "group.garagetab", "last_changed": "2017-02-08T12:56:03.848224+00:00", "last_updated":"2017-02-08T23:35:14.887961+00:00", "state": "open"}'

alert:
  garage_door:
    name: Garage is closed
    entity_id: cover.garage_door
    state: 'closed'
    repeat: 5
    can_acknowledge: true
    notifiers:
      - wb_slack


##########################################################################
#                               Includes                                ##
##########################################################################
sensor: !include sensors.yaml
automation: !include automation.yaml
#cover: !include cover.yaml
group: !include groups.yaml
script: !include scripts.yaml
shell_command: !include shell_commands.yaml

##########################################################################
##                               Enables                                ##
##########################################################################
conversation:
updater:
sun:
history:
discovery:
frontend:
logbook:
