homeassistant:
  # Name of the location where Home Assistant is running
  name: Conways
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # C for Celcius, F for Fahrenheit
  unit_system: imperial 
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

http:
  api_password: !secret api_password

media_player:
  platform: plex

climate:
  platform: radiotherm
  host: 
    - ***REMOVED***
  hold_temp: False

device_tracker:
  - platform: asuswrt
    host: ***REMOVED***
    username: !secret asus_username
    password: !secret asus_password
    protocol: telnet
  - platform: owntracks

input_select:
  who_cooks:
    name: Who cooks today
    options:
     - Mary
     - Michael
    initial: Mary
    icon: mdi:panda

mqtt:
  broker: ***REMOVED***17
  port: 1883
  client_id: pi-home-assistant
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

notify:
  name: wb_slack
  platform: slack
  api_key: !secret slack_api_key
  default_channel: '#home-automation'

automation:
  - alias: Michael's Presence
    trigger:
      platform: state
      entity_id: device_tracker.goibniu_goibniu
   #   from: 'not_home'
   #   to: 'home'
    action:
      service: notify.wb_slack
      data:
        message: Michael is {{ state(device_tracker.goibniu_goibniu) }}
  - alias: Update notifications
    trigger:
      platform: state
      entity_id: updater.updater
    action:
      service: notify.wb_slack
      data:
        message: 'There is a new Home Assistant release available.'

##########################################################################
#                               Includes                                ##
##########################################################################
sensor: !include sensors.yaml
cover: !include cover.yaml
group: !include groups.yaml

##########################################################################
##                               Enables                                ##
##########################################################################
conversation:
updater:
sun:
history:
discovery:
frontend:
logbook: