homeassistant:
  # Name of the location where Home Assistant is running
  name: Conways
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 1276
  # C for Celcius, F for Fahrenheit
  unit_system: imperial 
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  customize_domain: {}
  customize_glob: !include customize_glob.yaml
  packages: !include_dir_named packages

http:
  api_password: !secret api_password

frontend:
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
    - /local/custom_ui/state-card-custom_alarm.html
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles_es5.html
  themes:
    error:
      primary-color: red
    warn:
      primary-color: amber
    darkred: !include themes/darkred.yaml
    darkcyan: !include themes/darkcyan.yaml
    midnight: !include themes/midnight.yaml
    vintage: !include themes/vintage.yaml
  javascript_version: latest

media_player:
  platform: plex

tradfri:
  host: !secret tradfri_host

apcupsd:
  host: taranis

device_tracker:
  - platform: asuswrt
    host: !secret router_ip
    username: !secret asus_username
    password: !secret asus_password
    protocol: ssh
    track_new_devices: False
  - platform: owntracks

mqtt:
  broker: taranis
  port: 1883
  client_id: ha-host
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: "hass/status"
    payload: "online"

mqtt_eventstream:
  publish_topic: home/master
  subscribe_topic: home/slave

alarm_control_panel: !include alarm.yaml

recorder:
  db_url: !secret database_url
  purge_interval: 1
  purge_keep_days: 14
  exclude:
    domains:
      - alert
      - automation
      - sun
      - seasons
      - input_number
      - input_boolean
      - zone
    entities:
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_high_temperature_1
      - sensor.dark_sky_daily_high_temperature_2
      - sensor.dark_sky_daily_high_temperature_3
      - sensor.dark_sky_daily_high_temperature_4
      - sensor.dark_sky_daily_high_temperature_5
      - sensor.dark_sky_daily_high_temperature_6
      - sensor.dark_sky_daily_high_temperature_7
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_daily_low_temperature_1
      - sensor.dark_sky_daily_low_temperature_2
      - sensor.dark_sky_daily_low_temperature_3
      - sensor.dark_sky_daily_low_temperature_4
      - sensor.dark_sky_daily_low_temperature_5
      - sensor.dark_sky_daily_low_temperature_6
      - sensor.dark_sky_daily_low_temperature_7
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_humidity
      - sensor.dark_sky_humidity_1
      - sensor.dark_sky_humidity_2
      - sensor.dark_sky_humidity_3
      - sensor.dark_sky_humidity_4
      - sensor.dark_sky_humidity_5
      - sensor.dark_sky_humidity_6
      - sensor.dark_sky_humidity_7
      - sensor.dark_sky_icon
      - sensor.dark_sky_icon_1
      - sensor.dark_sky_icon_2
      - sensor.dark_sky_icon_3
      - sensor.dark_sky_icon_4
      - sensor.dark_sky_icon_5
      - sensor.dark_sky_icon_6
      - sensor.dark_sky_icon_7
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_1
      - sensor.dark_sky_precip_2
      - sensor.dark_sky_precip_3
      - sensor.dark_sky_precip_4
      - sensor.dark_sky_precip_5
      - sensor.dark_sky_precip_6
      - sensor.dark_sky_precip_7
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_intensity_1
      - sensor.dark_sky_precip_intensity_2
      - sensor.dark_sky_precip_intensity_3
      - sensor.dark_sky_precip_intensity_4
      - sensor.dark_sky_precip_intensity_5
      - sensor.dark_sky_precip_intensity_6
      - sensor.dark_sky_precip_intensity_7
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_probability_1
      - sensor.dark_sky_precip_probability_2
      - sensor.dark_sky_precip_probability_3
      - sensor.dark_sky_precip_probability_4
      - sensor.dark_sky_precip_probability_5
      - sensor.dark_sky_precip_probability_6
      - sensor.dark_sky_precip_probability_7
      - sensor.dark_sky_pressure
      - sensor.dark_sky_pressure_1
      - sensor.dark_sky_pressure_2
      - sensor.dark_sky_pressure_3
      - sensor.dark_sky_pressure_4
      - sensor.dark_sky_pressure_5
      - sensor.dark_sky_pressure_6
      - sensor.dark_sky_pressure_7
      - sensor.dark_sky_summary
      - sensor.dark_sky_temperature
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_bearing_1
      - sensor.dark_sky_wind_bearing_2
      - sensor.dark_sky_wind_bearing_3
      - sensor.dark_sky_wind_bearing_4
      - sensor.dark_sky_wind_bearing_5
      - sensor.dark_sky_wind_bearing_6
      - sensor.dark_sky_wind_bearing_7
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_speed_1
      - sensor.dark_sky_wind_speed_2
      - sensor.dark_sky_wind_speed_3
      - sensor.dark_sky_wind_speed_4
      - sensor.dark_sky_wind_speed_5
      - sensor.dark_sky_wind_speed_6
      - sensor.dark_sky_wind_speed_7
      - sensor.season
      - sensor.time
      - sensor.weekday
      - sensor.us_air_pollution_level
      - sensor.us_air_quality_index
      - sensor.us_main_pollutant

emulated_hue:
  exposed_domains:
    - light
    - cover
    - script
    - climate

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml
 # - name: alarm
 #   sidebar_title: Alarm
 #   sidebar_icon: mdi:security-home
 #   config:
 #     alarmid: alarm_control_panel.house ## USE THE SAME ID AS USED IN YOUR ALARM.YAML

influxdb:
  host: !secret influxdb_host
  username: !secret influxdb_username
  password: !secret influxdb_password
  database: !secret influxdb_database
  tags:
    instance: prod
    source: taranis
  tags_attributes:
    - friendly_name

##########################################################################
#                               Includes                                ##
##########################################################################
sensor: !include sensors.yaml
automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
shell_command: !include shell_commands.yaml

##########################################################################
##                               Enables                                ##
##########################################################################
conversation:
updater:
sun:
history:
discovery:
logbook:
config:
python_script: