homeassistant:
  # Name of the location where Home Assistant is running
  name: Conways
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 1276
  # C for Celcius, F for Fahrenheit
  unit_system: imperial 
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  customize_domain: {}
  customize_glob: !include customize_glob.yaml
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant
  whitelist_external_dirs: 
    - /config

http:
my:

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  #mode: yaml

mobile_app:

device_tracker:
  - platform: traccar
    host: traccar.wiredbyte.com
    username: !secret traccar_username 
    password: !secret traccar_password
    port: 443
    ssl: true
    verify_ssl: false

camera:
  - platform: generic
    still_image_url: https://images.wsdot.wa.gov/nc/028vc04659.jpg

recorder:
  db_url: !secret database_url
  purge_interval: 1
  purge_keep_days: 14
  exclude:
    domains:
      - alert
      - automation
      - sun
      - input_number
      - input_boolean
      - zone
    entities:
      - sensor.time
      - sensor.weekday
      - sensor.us_air_pollution_level
      - sensor.us_air_quality_index
      - sensor.us_main_pollutant

influxdb:
  api_version: 2
  ssl: false
  host: !secret influxdb_host
  token: !secret influxdb_password
  bucket: !secret influxdb_database
  organization: !secret influxdb_org
  port: 8086
  tags:
    instance: prod
    source: microk8s
  tags_attributes:
    - friendly_name

person:

system_health:

pi_hole:
  - host: pi.hole

##########################################################################
#                               Includes                                ##
##########################################################################
sensor: !include sensors.yaml
automation: !include automations.yaml
#group: !include groups.yaml
script: !include scripts.yaml
shell_command: !include shell_commands.yaml

##########################################################################
##                               Enables                                ##
##########################################################################
conversation:
backup:
sun:
map:
history:
discovery:
logbook:
config:
python_script: