homeassistant:
  # Name of the location where Home Assistant is running
  name: Conways
  # Location required to calculate the time the sun rises and sets
  latitude: ***REMOVED***
  longitude: ***REMOVED***
  # C for Celcius, F for Fahrenheit
  unit_system: imperial 
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize:
    device_tracker.aibell:
      hidden: true
    device_tracker.beansidhe:
      hidden: true
    device_tracker.camulos:
      hidden: true
    device_tracker.damara:
      hidden: true
    device_tracker.lugus:
      hidden: true
    device_tracker.taranis:
      hidden: true
    sensor.aibell:
      icon: mdi:laptop
    sensor.beansidhe:
      icon: mdi:tablet
    sensor.camulos:
      icon: mdi:desktop-tower
    sensor.damara:
      icon: mdi:tablet
    sensor.lugus:
      icon: mdi:printer
    sensor.taranis:
      icon: mdi:server
    sensor.speedtest_ping:
      friendly_name: 'Ping'
      icon: mdi:speedometer
    sensor.speedtest_download:
      friendly_name: 'Download'
      icon: mdi:speedometer
    sensor.speedtest_upload:
      friendly_name: 'Upload'
      icon: mdi:speedometer

http:
  api_password: ***REMOVED***

# Allows you to issue voice commands from the frontend
conversation:

# Checks for available updates
updater:

# Track the sun
sun:

# Enables support for tracking state changes over time.
history:

# Discover some devices automatically
discovery:

# Enables the frontend
frontend:

# View all events in a logbook
logbook:

media_player:
  platform: plex

thermostat:
  platform: radiotherm
  host: 
    - ***REMOVED***
  hold_temp: False

sensor:
  - platform: template
    sensors:
      aibell:
        friendly_name: 'Aibell'
        value_template: >-
          {%- if is_state("device_tracker.aibell", "home") %}
            Online
          {% else %}
            Offline
          {%- endif %}
      beansidhe:
        friendly_name: 'BeanSidhe'
        value_template: >-
          {%- if is_state("device_tracker.beansidhe", "home") %}
            Online
          {% else %}
            Offline
          {%- endif %}
      camulos:
        friendly_name: 'Camulos'
        value_template: >-
          {%- if is_state("device_tracker.camulos", "home") %}
            Online
          {% else %}
            Offline
          {%- endif %}
      damara:
        friendly_name: 'Damara'
        value_template: >-
          {%- if is_state("device_tracker.damara", "home") %}
            Online
          {% else %}
            Offline
          {%- endif %}
      lugus:
        friendly_name: 'Lugus'
        value_template: >-
          {%- if is_state("device_tracker.lugus", "home") %}
            Online
          {% else %}
            Offline
          {%- endif %}
      taranis:
        friendly_name: 'Taranis'
        value_template: >-
          {%- if is_state("device_tracker.taranis", "home") %}
            Online
          {% else %}
            Offline
          {%- endif %}
  - platform: speedtest
    minute: 30
    hour:
      - 0
      - 6
      - 12
      - 18
      - 21
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: fastdotcom
    minute: 5
  - platform: mqtt
    state_topic: "owntracks/goibniu/Goibniu"
    name: "Goibniu"
    unit_of_measurement: "%"
    value_template: '{{value_json.batt }}'
  - platform: forecast
    api_key: ***REMOVED***
    monitored_conditions:
      - summary
#      - icon
      - nearest_storm_distance
#      - nearest_storm_bearing
      - precip_type
#      - precip_intensity
      - precip_probability
      - temperature
#      - apparent_temperature
#      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
#      - visibility
#      - ozone

device_tracker:
  - platform: asuswrt
    host: ***REMOVED***
    username: ***REMOVED***
    password: ***REMOVED***
  - platform: owntracks

input_select:
  who_cooks:
    name: Who cooks today
    options:
     - Mary
     - Michael
    initial: Mary
    icon: mdi:panda

mqtt:
  broker: ***REMOVED***17
  port: 1883
  client_id: pi-home-assistant
  keepalive: 60
  username: ha-pi
  password: ***REMOVED***
  #certificate: /home/paulus/dev/addtrustexternalcaroot.crt
  #protocol: 3.1


notify:
  name: wb_slack
  platform: slack
  api_key: ***REMOVED***
  default_channel: '#home-automation'

group:
  Office:
    - device_tracker.goibniu_goibniu
    - device_tracker.goibniu
    - device_tracker.np12g2d0036416
    - device_tracker.android8069fa1e004161a7
    - sensor.camulos
    - sensor.lugus
    - sensor.taranis
  Internet:
    - device_tracker.dagda
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.speedtest_ping
  Devices:
    - sensor.aibell
    - sensor.beansidhe
    - sensor.damara

automation:
  trigger:
    platform: state
    entity_id: device_tracker.goibniu_goibniu
    # Optional
    from: 'not_home'
    to: 'home'
  action:
    service: notify.wb_slack
    data:
      message: Welcome Home!
