- platform: rpi_gpio
  covers:
     relay_pin: 23
     state_pin: 17
     name: 'Garage Door'
- platform: command_line
  covers:
    dummy:
      command_open: move_command up garage
      command_close: move_command up garage
      command_stop: move_command up garage
