####################
#
# UI-Lovelace-Minimalist CodeGenerator Example
#
# Author: Paddy0174
#
####################
button_card_templates: !include_dir_merge_named minimalist-templates/
views:
- title: Minimalist
  path: lovelace-minimalist
  badges: []
  cards:
    - type: vertical-stack
      cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge

          - type: 'custom:button-card'
            template: chip_back
            variables:
              ulm_chip_back_path: /ui-lovelace-minimalist/home

          - type: 'custom:button-card'
            template: chip_temperature
            variables:
              ulm_chip_temperature_inside: sensor.4_in_1_sensor_air_temperature
              ulm_chip_temperature_outside: sensor.4_in_1_sensor_air_temperature_2
              ulm_chip_temperature_weather: weather.home

          - type: custom:button-card
            template: edge

      - type: custom:swipe-card
        start_card: 2
        reset_after: 30
        parameters:
          spaceBetween: 8
          autoHeight: true
          pagination:
            type: bullets
        cards:
          - type: picture-glance
            aspect_ratio: '16:9'
            camera_image: camera.balor_driveway
            camera_view: live
            entities: []
            name: Driveway
            card_mod:
              style: |
                ha-card {
                  margin-bottom: 15px;
                  background: rgba(255, 255, 255, 0.0);
                  border-radius: 0;
                  box-shadow: none;
                  color: white;
                }
                .box {
                  background: rgba(255,255,255,0) !important;
                }
          - type: markdown
            content: >
              <table> <tr><td width="200px"><h3>{{
              states('sensor.dashboard_greeting') }}, {{ user
              }}</h3><strong>Current Temperature:</strong>
              {{state_attr('weather.home','temperature') |
              round}}&deg;F</br> {% if is_state("sun.sun", "above_horizon")
              -%}
                <strong>Next Sunset:</strong> {{as_timestamp(strptime(state_attr("sun.sun", "next_setting"), '')) | timestamp_custom("%-I:%M %p")}}
              {%- else -%}
                  <strong>Next Sunrise:</strong> {{as_timestamp(strptime(state_attr("sun.sun", "next_rising"), '')) | timestamp_custom("%-I:%M %p")}}
              {%- endif %}</br></br><strong>SmartHome Mode:</strong> {{ 
              states('input_text.home_mode') }}</br> <strong>Doors:</strong>
              {{ states('sensor.door_locks') }}</br> <strong>Grocery
              Budget:</strong> ${{ states('sensor.grocery_budget_balance')
              }} </td><td></br><img
              src="https://darksky.net/{{states('sensor.dashboard_weather')}}"
              width="190px" /></td></tr> <tr><td colspan="2">{{
              states('sensor.dashboard_occupancy') }}</td></tr></table></br>
            style: |
              ha-card {
                background: transparent;
                margin-top: -15px;
                margin-bottom: -7px;
              }
          - type: picture-glance
            aspect_ratio: '16:9'
            camera_image: camera.balor_front_porch
            camera_view: live
            entities: []
            name: Front Door
            card_mod:
              style: |
                ha-card {
                  margin-bottom: 15px;
                  background: rgba(255, 255, 255, 0.0);
                  border-radius: 0;
                  box-shadow: none;
                  color: white;
                 }
                .box {
                  background: rgba(255,255,255,0) !important;
                }
          - type: area
            area: office

      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge

          - type: 'custom:button-card'
            template: card_title
            name: Rooms

          - type: custom:button-card
            template: edge

      - type: custom:swipe-card
        reset_after: 30
        parameters:
          spaceBetween: 0
          autoHeight: true
          pagination:
            type: none
        cards:
          - type: horizontal-stack
            cards:
            - type: custom:button-card
              template: edge

            - type: custom:button-card
              template: vertical_buttons
              entity: binary_sensor.4_in_1_sensor_home_security_motion_detection
              #show_entity_picture: true
              #entity_picture: "/api/image/serve/b3a5a7eb77afde484cdc889b1b36f653/512x512"
              name: Office
              icon: mdi:sword-cross
              show_last_changed: true

            - type: custom:button-card
              template: vertical_buttons
              entity: switch.in_wall_paddle
              name: Patio
              icon: mdi:string-lights

            - type: custom:button-card
              template: vertical_buttons
              entity: switch.in_wall_paddle
              name: Patio
              icon: mdi:string-lights

            - type: custom:button-card
              template: edge

          - type: horizontal-stack
            cards:
            - type: custom:button-card
              template: edge

            - type: custom:button-card
              template: vertical_buttons
              entity: switch.in_wall_paddle
              name: Patio
              icon: mdi:string-lights

            - type: custom:button-card
              template: vertical_buttons
              entity: switch.in_wall_paddle
              name: Patio
              icon: mdi:string-lights

            - type: custom:button-card
              template: vertical_buttons
              entity: switch.in_wall_paddle
              name: Patio
              icon: mdi:string-lights

            - type: custom:button-card
              template: edge

      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge

          - type: 'custom:button-card'
            template: card_title
            name: Back Yard

          - type: custom:button-card
            template: edge

      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge

          - type: custom:button-card
            template: vertical_buttons
            entity: switch.in_wall_switch_on_off
            name: Front Porch
            icon: mdi:outdoor-lamp

          - type: custom:button-card
            template: vertical_buttons
            entity: switch.in_wall_paddle
            name: Patio
            icon: mdi:string-lights

          - type: custom:button-card
            template: vertical_buttons
            entity: switch.multirelay_2_2
            name: Deck Stairs
            icon: mdi:stairs

          - type: custom:button-card
            template: vertical_buttons
            entity: switch.multirelay_2
            name: Deck Lights
            icon: mdi:patio-heater

          - type: custom:button-card
            template: edge

      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge

          - type: custom:button-card
            template: custom_card_paddy_welcome_with_weather
            variables:
              - ulm_custom_card_paddy_welcome_weather_provider: weather.home
              - ulm_custom_card_paddy_welcome_time: sensor.time

          - type: custom:button-card
            variables:
              name: "Living Room"
              label: "3 Devices"
              path: "/lovelace/living_room"
            template:
              - icon_info_bg
              - room
          - type: custom:button-card
            variables:
              name: "Bureau"
              label: "6 Devices"
              path: "/lovelace/bureau"
              image: "/local/images/tiles/desk.jpg"
            template:
              - icon_info_bg
              - room

          - type: custom:button-card
            template: edge

      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge

          - type: 'custom:button-card'
            template: card_title
            name: Office
            label: >
              [[[
                return states['device_tracker.camulos'].state  
              ]]]

          - type: custom:button-card
            template: edge


      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge

          #- type: 'custom:button-card'
          #  template: card_battery
#           variables:
#            ulm_card_battery_attribute: battery_attribute
          #  entity: sensor.4_in_1_sensor_battery_level

          #- type: 'custom:button-card'
          #  template: card_script
          #  variables: 
          #    ulm_card_script_title: Romantic lights
          #    ulm_card_script_icon: 'mdi:candle'
          #  tap_action:
          #    action: call-service
          #    service: script.turn_on
          #    service_data: 
          #      entity_id: script.romantic_livingroom_lights

          - type: 'custom:button-card'
            template: card_light
            entity: light.red_series_fan_light_switch_2
            icon: mdi:ceiling-fan-light
            name: Fan Light

          - type: 'custom:button-card'
            template: card_light
            entity: fan.red_series_fan_light_switch_2
            icon: mdi:ceiling-fan
            name: Fan

          - type: 'custom:button-card'
            template: card_power_outlet
            variables:
              ulm_card_power_outlet_consumption_sensor: sensor.power_switch_electric_consumption_kwh 
            entity: switch.power_switch
            name: Artemis
            icon: mdi:printer-3d

          - type: custom:button-card
            template: edge

      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge

          - type: 'custom:button-card'
            template: card_light_slider_collapse
            entity: light.office_left

          - type: 'custom:button-card'
            template: card_binary_sensor_alert
            variables:
              - ulm_card_binary_sensor_alert: true
            entity: binary_sensor.4_in_1_sensor_home_security_motion_detection
            show_last_changed: true
            name: Motion

          - type: 'custom:button-card'
            template: card_light_slider_collapse
            entity: light.office_right

          - type: custom:button-card
            template: edge

      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge

          - type: 'custom:button-card'
            template: card_title
            name: People
            label: 'Subtitle'  

          - type: custom:button-card
            template: edge

      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_person
            variables:
              ulm_card_person_entity: person.mick
          - type: 'custom:button-card'
            template: card_person
            variables:
              ulm_card_person_entity: person.aiden
          - type: custom:button-card
            template: edge

      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_person
            variables:
              ulm_card_person_entity: person.aiden
          - type: 'custom:button-card'
            template: card_person
            variables:
              ulm_card_person_entity: person.lilly
          - type: custom:button-card
            template: edge
