- platform: template
  sensors:
    aibell:
      friendly_name: 'Aibell'
      value_template: >-
        {%- if is_state("device_tracker.aibell", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %}
    beansidhe:
      friendly_name: 'BeanSidhe'
      value_template: >-
        {%- if is_state("device_tracker.beansidhe", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %}
    camulos:
      friendly_name: 'Camulos'
      value_template: >-
        {%- if is_state("device_tracker.camulos", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %}
    damara:
      friendly_name: 'Damara'
      value_template: >-
        {%- if is_state("device_tracker.damara", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %}
    lugus:
      friendly_name: 'Lugus'
      value_template: >-
        {%- if is_state("device_tracker.lugus", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %}
    maponos:
      friendly_name: 'Maponos'
      value_template: >-
        {%- if is_state("device_tracker.maponos", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %}
      icon_template: >-
        {%- if is_state("device_tracker.maponos", "home") %}
          mdi:power
        {% else %}
          mdi:power-plug-off
        {%- endif %}
    nodens:
      friendly_name: 'Nodens'
      value_template: >-
        {%- if is_state("device_tracker.nodens", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %}
      icon_template: >-
        {%- if is_state("device_tracker.nodens", "home") %}
          mdi:power
        {% else %}
          mdi:power-plug-off
        {%- endif %}
    taranis:
      friendly_name: 'Taranis'
      value_template: >-
        {%- if is_state("device_tracker.taranis", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %}      
      icon_template: >-
        {%- if is_state("device_tracker.taranis", "home") %}
          mdi:power
        {% else %}
          mdi:power-plug-off
        {%- endif %}
    home:
      friendly_name: "Home Temp"
      value_template: '{{ states.climate.home.attributes["current_temperature"] }}'
    roku:
      friendly_name: Roku
      value_template: >-
        {% if is_state("device_tracker.np12g2d0036416", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %}
    nintendoswitch:
      friendly_name: "Nintendo Switch"
      value_template: >-
        {% if is_state("device_tracker.dc68eb5a2d02", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %}
    wii:
      friendly_name: "Wii"
      value_template: >-
        {%- if is_state("device_tracker.wii", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %} 
    xboxone:
      friendly_name: "Xbox One"
      value_template: >-
        {%- if is_state("device_tracker.xboxsystemos_2", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %} 
    battery_goibniu:
      friendly_name: Goibniu Battery
      # "entity_id:" ensures that this sensor will only update when your device tracker does.
      entity_id: device_tracker.goibniu_goibniu
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.device_tracker.goibniu_goibniu.attributes.battery %}
              {{ states.device_tracker.goibniu_goibniu.attributes.battery|round }}
          {% else %}
              {{ states.sensor.battery_goibniu_goibniu.state }}
          {%- endif %}
      icon_template: >
          {% set battery_level = states.sensor.battery_goibniu_goibniu.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
    battery_aiden:
      friendly_name: Aiden Battery
      # "entity_id:" ensures that this sensor will only update when your device tracker does.
      entity_id: device_tracker.aidenphone_aidenphone
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.device_tracker.aidenphone_aidenphone.attributes.battery %}
              {{ states.device_tracker.aidenphone_aidenphone.attributes.battery|round }}
          {% else %}
              {{ states.sensor.battery_aidenphone_aidenphone.state }}
          {%- endif %}
      icon_template: >
          {% set battery_level = states.sensor.battery_aidenphone_aidenphone.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}

    # https://community.home-assistant.io/t/system-monitoring-how-does-your-look/109713/260
    #----- Count All Entities
    total_entities:
      friendly_name: 'Entities'
      icon_template: mdi:code-tags
      value_template: "{{ states | count }}"

    #----- Count Automations
    total_automations:
      friendly_name: 'Automations'
      icon_template: mdi:robot
      value_template: "{{ states.automation | list | length }}"

    #----- Count Binary Sensors
    total_binary_sensors:
      friendly_name: 'Binary Sensors'
      icon_template: mdi:checkbox-multiple-marked-circle # mdi:unfold-less-horizontal
      value_template: "{{ states.binary_sensor | list | length }}"

    #----- Count Binary Sensors
    total_cameras:
      friendly_name: 'Cameras'
      icon_template: mdi:cctv
      value_template: "{{ states.camera | list | length }}"

    #----- Count Device Trackers
    total_devicetrackers:
      friendly_name: 'Devices'
      icon_template: mdi:cellphone-link
      value_template: "{{ states.device_tracker | list | length }}"

    #----- Count Input Booleans
    total_input_booleans:
      friendly_name: 'Input Booleans'
      icon_template: mdi:toggle-switch
      value_template: "{{ states.input_boolean | list | length }}"

    #----- Count Input Numbers
    total_input_numbers:
      friendly_name: 'Input Numbers'
      icon_template: mdi:numeric
      value_template: "{{ states.input_number | list | length }}"

    #----- Count Input Selects
    total_input_selects:
      entity_id: sensor.date
      friendly_name: 'Input Selects'
      icon_template: mdi:format-align-justify
      value_template: "{{ states.input_select | list | length }}"

    #----- Count Input Texts
    total_input_texts:
      friendly_name: 'Input Texts'
      icon_template: mdi:alphabetical
      value_template: "{{ states.input_text | list | length }}"

    #----- Count Lights
    total_lights:
      entity_id: sensor.date
      friendly_name: 'Lights'
      icon_template: mdi:lightbulb-on
      value_template: "{{ states.light | list | length }}"

    #----- Count Media Players
    total_media_players:
      friendly_name: 'Media Players'
      icon_template: mdi:cast-connected
      value_template: "{{ states.media_player | list | length }}"

    #----- Count Scripts
    total_scripts:
      friendly_name: 'Scripts'
      icon_template: mdi:script-text-outline
      value_template: "{{ states.script | list | length }}"

    #----- Count Sensors
    total_sensors:
      friendly_name: 'Sensors'
      icon_template: mdi:pulse
      value_template: "{{ states.sensor | list | length }}"

    #----- Count Switches
    total_switches:
      friendly_name: 'Switches'
      icon_template: mdi:power-socket-us
      value_template: "{{ states.switch | list | length }}"

    #----- Count Zones
    total_zones:
      friendly_name: 'Zones'
      icon_template: mdi:map-marker-radius
      value_template: "{{ states.zone | list | length }}"

    #----- Count Z-Wave Devices
    total_zwave_devices:
      friendly_name: 'ZWave'
      icon_template: mdi:z-wave
      value_template: "{{ states.zwave | list | length }}"
        
#- platform: mqtt#
#  state_topic: "owntracks/goibniu/Goibniu"
#  name: "Goibniu"
#  unit_of_measurement: "%"
#  value_template: '{{value_json.batt }}'
- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
- platform: time_date
  display_options:
    - time
    - date
    - date_time
- platform: moon
- platform: steam_online
  api_key: !secret steam_api_key
  accounts:
    - !secret mike_steam_id
    - !secret mary_steam_id
    - !secret aiden_steam_id
    - !secret lilly_steam_id
- platform: xbox_live
  api_key: !secret xbox_api_key
  xuid:
    - !secret xbox_mike_uid
- platform: apcupsd
  resources:
    - model
    - status
    - linev
    - loadpct
    - numxfers
    - bcharge
    - timeleft
    - battv
    - tonbatt

# Version checking Sensors
- platform: version
  name: latest_version
  source: docker
- platform: version
  name: current_version
  source: local

# Misc System Sensors
- platform: filesize
  file_paths:
    - /config/home-assistant.log
- platform: sql
  db_url: !secret database_url
  queries:
    - name: Database Size
      query: "SELECT table_schema 'DB Name', ROUND(SUM(data_length + index_length) / 1024 / 1024, 1) 'MB' FROM information_schema.tables WHERE table_schema='homeassistant' GROUP BY table_schema;"
      column: 'MB'
      unit_of_measurement: 'MB'
- platform: dnsip
  resolver: 10.10.1.190

