- platform: template
  sensors:
    aibell:
      friendly_name: 'Aibell'
      value_template: >-
        {%- if is_state("device_tracker.aibell", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %}
    beansidhe:
      friendly_name: 'BeanSidhe'
      value_template: >-
        {%- if is_state("device_tracker.beansidhe", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %}
    camulos:
      friendly_name: 'Camulos'
      value_template: >-
        {%- if is_state("device_tracker.camulos", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %}
    damara:
      friendly_name: 'Damara'
      value_template: >-
        {%- if is_state("device_tracker.damara", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %}
    lugus:
      friendly_name: 'Lugus'
      value_template: >-
        {%- if is_state("device_tracker.lugus", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %}
    maponos:
      friendly_name: 'Maponos'
      value_template: >-
        {%- if is_state("device_tracker.maponos", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %}
      icon_template: >-
        {%- if is_state("device_tracker.maponos", "home") %}
          mdi:power
        {% else %}
          mdi:power-plug-off
        {%- endif %}
    nodens:
      friendly_name: 'Nodens'
      value_template: >-
        {%- if is_state("device_tracker.nodens", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %}
      icon_template: >-
        {%- if is_state("device_tracker.nodens", "home") %}
          mdi:power
        {% else %}
          mdi:power-plug-off
        {%- endif %}
    taranis:
      friendly_name: 'Taranis'
      value_template: >-
        {%- if is_state("device_tracker.taranis", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %}      
      icon_template: >-
        {%- if is_state("device_tracker.taranis", "home") %}
          mdi:power
        {% else %}
          mdi:power-plug-off
        {%- endif %}
    home:
      friendly_name: "Home Temp"
      value_template: '{{ states.climate.home.attributes["current_temperature"] }}'
    roku:
      friendly_name: Roku
      value_template: >-
        {% if is_state("device_tracker.np12g2d0036416", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %}
    nintendoswitch:
      friendly_name: "Nintendo Switch"
      value_template: >-
        {% if is_state("device_tracker.dc68eb5a2d02", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %}
    wii:
      friendly_name: "Wii"
      value_template: >-
        {%- if is_state("device_tracker.wii", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %} 
    xboxone:
      friendly_name: "Xbox One"
      value_template: >-
        {%- if is_state("device_tracker.xboxsystemos_2", "home") %}
          Online
        {% else %}
          Offline
        {%- endif %} 
    battery_goibniu:
      friendly_name: Goibniu Battery
      # "entity_id:" ensures that this sensor will only update when your device tracker does.
      entity_id: device_tracker.goibniu_goibniu
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.device_tracker.goibniu_goibniu.attributes.battery %}
              {{ states.device_tracker.goibniu_goibniu.attributes.battery|round }}
          {% else %}
              {{ states.sensor.battery_goibniu_goibniu.state }}
          {%- endif %}
      icon_template: >
          {% set battery_level = states.sensor.battery_goibniu_goibniu.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
    battery_aiden:
      friendly_name: Aiden Battery
      # "entity_id:" ensures that this sensor will only update when your device tracker does.
      entity_id: device_tracker.aidenphone_aidenphone
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.device_tracker.aidenphone_aidenphone.attributes.battery %}
              {{ states.device_tracker.aidenphone_aidenphone.attributes.battery|round }}
          {% else %}
              {{ states.sensor.battery_aidenphone_aidenphone.state }}
          {%- endif %}
      icon_template: >
          {% set battery_level = states.sensor.battery_aidenphone_aidenphone.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        
- platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
    - 21
  monitored_conditions:
    - ping
    - download
    - upload
#- platform: mqtt#
#  state_topic: "owntracks/goibniu/Goibniu"
#  name: "Goibniu"
#  unit_of_measurement: "%"
#  value_template: '{{value_json.batt }}'
- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /
    - type: memory_free
    - type: processor_use
    - type: last_boot
- platform: time_date
  display_options:
    - time
    - date
    - date_time
- platform: moon
- platform: steam_online
  api_key: !secret steam_api_key
  accounts:
    - !secret mike_steam_id
    - !secret mary_steam_id
    - !secret aiden_steam_id
    - !secret lilly_steam_id
- platform: xbox_live
  api_key: !secret xbox_api_key
  xuid:
    - !secret xbox_mike_uid
- platform: apcupsd
  resources:
    - model
    - status
    - linev
    - loadpct
    - numxfers
    - bcharge
    - timeleft
    - battv
    - tonbatt