name: My Awesome Home
views:
    # Specify a tab_icon if you want the view tab to be an icon.
  - tab_icon: mdi:home-assistant
    # Name of the view. Will be used as the tooltip for tab icon
    name: Home
    cards:
      - type: picture-entity
        entity: camera.front_porch
      - type: picture-entity
        entity: camera.driveway
      - type: weather-forecast
        entity: weather.darksky