name: My Awesome Home
views:
    # Specify a tab_icon if you want the view tab to be an icon.
  - icon: mdi:home-assistant
    # Name of the view. Will be used as the tooltip for tab icon
    name: Home
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: picture-elements
                image: https://home.wiredbyte.com/s/88dDxDBjkkWzB9T/preview
                elements:
                  - type: state-icon
                    entity: device_tracker.goibniu_goibniu
                    style:
                      top: 90%
                      left: 10%
                  - type: state-label
                    entity: device_tracker.goibniu_goibniu
                    style:
                      top: 90%
                      left: 30%
                  - type: state-icon
                    entity: sensor.battery_goibniu
                    style:
                      top: 90%
                      left: 75%
                  - type: state-label
                    entity: sensor.battery_goibniu
                    style:
                      top: 90%
                      left: 90%
              - type: picture-glance
                image: https://home.wiredbyte.com/s/35c3ryFePnAKPSF/preview
                title: Mary
                entities:
                  - device_tracker.android1b27fe99b8b39bc3
              - type: picture-elements
                image: https://home.wiredbyte.com/s/B3zDH6TWYRWTRQ8/preview
                elements:
                  - type: state-icon
                    entity: device_tracker.aidenphone_aidenphone
                    style:
                      top: 90%
                      left: 10%
                  - type: state-label
                    entity: device_tracker.aidenphone_aidenphone
                    style:
                      top: 90%
                      left: 30%
                  - type: state-icon
                    entity: sensor.battery_aiden
                    style:
                      top: 90%
                      left: 75%
                  - type: state-label
                    entity: sensor.battery_aiden
                    style:
                      top: 90%
                      left: 90%
              - type: picture-glance
                image: https://home.wiredbyte.com/s/35c3ryFePnAKPSF/preview
                title: Mary
                entities:
                  - device_tracker.android1b27fe99b8b39bc3

          - type: horizontal-stack
            cards:
              - type: media-control
                entity: media_player.master_bedroom
              - type: media-control
                entity: media_player.kitchen
          - type: horizontal-stack
            cards:
              - type: media-control
                entity: media_player.aidens_room
              - type: media-control
                entity: media_player.lillys_room

      - type: weather-forecast
        entity: weather.dark_sky

      - type: horizontal-stack
        cards:
          - type: light
            entity: light.office
          - type: light
            entity: light.back_room
          - type: light
            entity: light.master_bedroom
            name: Master
          - type: entity-button
            entity: lock.kwikset_unknown_type0003_id0541_locked_2

      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: lock.kwikset_unknown_type0003_id0541_locked_2

      - type: entity-filter
        entities:
          - sensor.steam_76561197993153035
          - sensor.steam_76561198355581858
          - sensor.steam_76561198402756271
          - sensor.steam_76561198008190846
        state_filter:
          - 'online'
          - 'busy'
          - 'away'
          - 'snooze'
          - 'looking_to_trade'
          - 'looking_to_play'
        card:
          type: glance
          title: Steam
        show_empty: false
      - type: thermostat
        entity: climate.home

  - icon: mdi:settings
    name: System Status
    cards:
      - type: vertical-stack
        cards:  
          - type: picture-elements
            image: /local/lovelace/system/isp_4.png
            #title: Internet
            elements:
            - type: state-icon
              entity: sensor.speedtest_ping
              style:
                top: 85%
                left: 25%
                
            - type: state-label 
              entity: sensor.speedtest_ping
              prefix: "Internet : " 
              style:
                top: 93%
                left: 20%
                font-size: 115%
                font-weight: bold
                
            - type: state-icon
              entity: sensor.speedtest_download
              style:
                top: 85%
                left: 50%
                
            - type: state-label 
              entity: sensor.speedtest_download
              style:
                top: 93%
                left: 50%
                font-size: 115%
                font-weight: bold
                
            - type: state-icon
              entity: sensor.speedtest_upload
              style:
                top: 85%
                left: 75%
                
            - type: state-label 
              entity: sensor.speedtest_upload
              style:
                top: 93%
                left: 75%
                font-size: 115%
                font-weight: bold

      - type: picture-elements
        image: https://home.wiredbyte.com/s/kCLQMJjaZDK2imc/preview
        elements:
          - type: state-icon
            entity: sensor.memory_free
            style:
              top: 80%
              left: 33.3%
          - type: state-label
            entity: sensor.memory_free
            style:
              top: 90%
              left: 33.3%
              text-shadow: 2px 2px black
              font-family: Trebuchet MS
              font-size: 90%
              font-weight: 550
          - type: state-icon
            entity: sensor.last_boot
            style:
              top: 80%
              left: 50%
          - type: state-label
            entity: sensor.last_boot
            style:
              top: 90%
              left: 50%
              text-shadow: 2px 2px black
              font-family: Trebuchet MS
              font-size: 90%
              font-weight: 550
          - type: state-icon
            entity: sensor.disk_free_
            style:
              top: 80%
              left: 66.6%
          - type: state-label
            entity: sensor.disk_free_
            style:
              top: 90%
              left: 66.6%
              text-shadow: 2px 2px black
              font-family: Trebuchet MS
              font-size: 90%
              font-weight: 550

  - icon: mdi:shield-outline
    name: Security
    cards:
      - type: alarm-panel
        title: House Alarm
        entity: alarm_control_panel.house
      - type: entities
        title: Sensors
        entities:
          - binary_sensor.dome_doorwindow_sensor_sensor
          - sensor.front_door
          - cover.garage_door
      - type: glance
        title: Battery Levels
        entities:
          - sensor.front_door_battery
          - sensor.siren_battery
      - type: horizontal-stack
        cards:
          - type: picture-entity
            entity: camera.front_porch
          - type: picture-entity
            entity: camera.driveway

      
