name: My Awesome Home
views:
    # Specify a tab_icon if you want the view tab to be an icon.
  - tab_icon: mdi:home-assistant
    # Name of the view. Will be used as the tooltip for tab icon
    name: Home
    cards:
      - type: horizontal-stack
        cards:
          - type: picture-elements
            image: https://home.wiredbyte.com/s/88dDxDBjkkWzB9T/preview
            elements:
              - type: state-icon
                entity: device_tracker.goibniu_goibniu
                style:
                  top: 90%
                  left: 10%
              - type: state-label
                entity: device_tracker.goibniu_goibniu
                style:
                  top: 90%
                  left: 30%
              - type: state-icon
                entity: sensor.battery_goibniu
                style:
                  top: 90%
                  left: 75%
              - type: state-label
                entity: sensor.battery_goibniu
                style:
                  top: 90%
                  left: 90%
          - type: picture-glance
            image: https://home.wiredbyte.com/s/35c3ryFePnAKPSF/preview
            title: Mary
            entities:
              - device_tracker.android1b27fe99b8b39bc3
          - type: picture-elements
            image: https://home.wiredbyte.com/s/B3zDH6TWYRWTRQ8/preview
            elements:
              - type: state-icon
                entity: device_tracker.aidenphone_aidenphone
                style:
                  top: 90%
                  left: 10%
              - type: state-label
                entity: device_tracker.aidenphone_aidenphone
                style:
                  top: 90%
                  left: 30%
              - type: state-icon
                entity: sensor.battery_aiden
                style:
                  top: 90%
                  left: 75%
              - type: state-label
                entity: sensor.battery_aiden
                style:
                  top: 90%
                  left: 90%

      - type: weather-forecast
        entity: weather.dark_sky

      - type: picture-elements
        image: https://home.wiredbyte.com/s/kCLQMJjaZDK2imc/preview
        elements:
          - type: state-icon
            entity: sensor.memory_free
            style:
              top: 80%
              left: 33.3%
          - type: state-label
            entity: sensor.memory_free
            style:
              top: 90%
              left: 33.3%
              text-shadow: 2px 2px black
              font-family: Trebuchet MS
              font-size: 90%
              font-weight: 550
          - type: state-icon
            entity: sensor.last_boot
            style:
              top: 80%
              left: 50%
          - type: state-label
            entity: sensor.last_boot
            style:
              top: 90%
              left: 50%
              text-shadow: 2px 2px black
              font-family: Trebuchet MS
              font-size: 90%
              font-weight: 550
          - type: state-icon
            entity: sensor.disk_free_
            style:
              top: 80%
              left: 66.6%
          - type: state-label
            entity: sensor.disk_free_
            style:
              top: 90%
              left: 66.6%
              text-shadow: 2px 2px black
              font-family: Trebuchet MS
              font-size: 90%
              font-weight: 550

      - type: horizontal-stack
        cards:
        - type: horizontal-stack
          cards:
            - type: picture-entity
              entity: camera.front_porch
            - type: picture-entity
              entity: camera.driveway

      - type: glance
        title: Battery Levels
        entities:
          - sensor.front_door_battery
          - sensor.siren_battery

      - type: entity-filter
        entities:
          - sensor.steam_76561197993153035
          - sensor.steam_76561198355581858
          - sensor.steam_76561198402756271
          - sensor.steam_76561198008190846
        state_filter:
          - 'online'
          - 'busy'
          - 'away'
          - 'snooze'
          - 'looking_to_trade'
          - 'looking_to_play'
        card:
          type: glance
          title: Steam
        show_empty: false
    
      - type: media-control
        entity: media_player.aidens_room
      - type: media-control
        entity: media_player.lillys_room
      - type: media-control
        entity: media_player.master_bedroom
      - type: media-control
        entity: media_player.kitchen