alias: Reload Core Config
sequence:
- event: LOGBOOK_ENTRY
  event_data:
    name: EVENT
    message: "Reloading Home Assistant Core Config"
- service: notify.slack
  data:
    message: ":recycle: Reloading Home Assistant Core Config" #at {{ states('sensor.date__time') }}
- service: homeassistant.reload_core_config