alias: Update Configs
sequence:
- event: LOGBOOK_ENTRY
  event_data:
    name: EVENT
    message: "Updating config"
- service: notify.slack
  data:
    message: ":recycle: Pulling latest configuration files from git repo" #at {{ states('sensor.date__time') }}
- service: shell_command.update_configs_from_repo
- condition: state
  entity_id: input_boolean.restart_on_config_update
  state: 'on'
- service: script.restart_ha