homeassistant:
  customize:
  # Control Panel
    script.remote_control:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 7
        row_height: 75px
        column_width: 62px
        gap: 15px
        color: '#555B65'
        color_on: '#00CC33'
        #color_on: 'var(--primary-color)'
        #color_on: '#262B38'
        color_off: '#BBBEC2'
        entities:
          # Favorites
          - entity: script.restart_ha
            icon: mdi:restart
            column: 1
            row: 1
          - entity: script.update_config
            icon: mdi:git
            column: 2
            row: 1
          - entity: script.reload_config
            icon: mdi:update
            column: 3
            row: 1
          - entity: script.upgrade_ha
            icon: mdi:robot
            column: 4
            row: 1

          #second row
          - entity: sensor.taranis
            icon: mdi:linux
            column: 1
            row: 2
          - entity: sensor.camulos
            icon: mdi:windows
            column: 2
            row: 2
          - entity: sensor.xboxone
            icon: mdi:xbox
            column: 4
            row: 2
          - entity: sensor.nintendoswitch
            icon: mdi:nintendo-switch
            column: 5
            row: 2
          - entity: sensor.wii
            icon: mdi:wii
            column: 6
            row: 2 

script:
  remote_control:
    sequence:

group:
  remote_control:
    name: Control Panel
    entities:
      - script.remote_control