homeassistant:
  customize:
  # Control Panel
    script.admin_control:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 7
        row_height: 75px
        column_width: 62px
        gap: 15px
        color: '#555B65'
        color_on: '#00CC33'
        #color_on: 'var(--primary-color)'
        #color_on: '#262B38'
        color_off: '#BBBEC2'
        entities:
          # Favorites
          - entity: script.restart_ha
            icon: mdi:restart
            column: 1
            row: 1
          - entity: script.update_config
            icon: mdi:git
            column: 2
            row: 1
          - entity: script.reload_config
            icon: mdi:update
            column: 3
            row: 1
          - entity: script.upgrade_ha
            icon: mdi:home-assistant
            column: 4
            row: 1

script:
  admin_control:
    sequence:

group:
  admin_control:
    name: Admin Panel
    entities:
      - script.admin_control