climate:
  platform: honeywell
  username: !secret thermostat_username
  password: !secret thermostat_password
  region: us
  scan_interval: 60

automation:
  - id: notify_thermostat_change
    alias: Notify Thermostat Change
    trigger:
      platform: state
      entity_id: climate.home
    condition:
      condition: template
      value_template: '{{ trigger.from_state.attributes.temperature != trigger.to_state.attributes.temperature }}'
    action:
      service: notify.slack
      data_template: 
        message: ':fire: Thermostat changed (From {{ trigger.from_state.attributes.temperature }} to {{ trigger.to_state.attributes.temperature }})'
