climate:
  platform: honeywell
  username: !secret thermostat_username
  password: !secret thermostat_password
  region: us
  scan_interval: 60
  cool_away_temperature: 80
  heat_away_temperature: 60

automation:
  - id: notify_thermostat_change
    alias: Notify Thermostat Change
    trigger:
      platform: state
      entity_id: climate.home
    condition:
      condition: template
      value_template: '{{ trigger.from_state.attributes.temperature != trigger.to_state.attributes.temperature }}'
    action:
      service: notify.default_group
      data_template: 
        message: ':fire: Thermostat changed (From {{ trigger.from_state.attributes.temperature }} to {{ trigger.to_state.attributes.temperature }})'
        target: [
          "448389226078273537"
        ]
  - id: climate_away
    alias: Climate Away
    trigger:
      platform: state
      entity_id: group.people
      to: 'not_home'
      for:
        hours: 0
        minutes: 30
        seconds: 0
    action:
      - service: climate.set_away_mode
        data:
          entity_id: climate.home
          away_mode: 'on'
      - service: notify.default_group
        data:
         message: ':fire: House empty for 30 minutes, setting thermostat to Away mode'
         target: [
            "448389226078273537"
          ]
  - id: climate_home
    alias: Climate Home
    trigger:
      platform: state
      entity_id: group.people
      to: 'home'
    action:
      - service: climate.set_away_mode
        data:
          entity_id: climate.home
          away_mode: 'off'
      - service: notify.slack
        data:
         message: ':fire: Disabling thermostat away mode'
