homeassistant:
  customize:
    sensor.duet_status:
      friendly_name: '3D Printer Status'
      icon: mdi:printer-3d

sensor:
  - platform: rest
    name: Duet Status
    resource: http://taranis:1880/duet3d
    value_template: '{{ value_json.status }}'
    json_attributes:
      - temps
      - fractionPrinted
  - platform: template
    sensors:
      head_temp_current:
        value_template: '{{ states.sensor.duet_status.attributes.temps.tools.active[0][0] }}'
      head_temp_active:
        value_template: '{{ states.sensor.duet_status.attributes.temps.tools.standby[0][0] }}'
      bed_temp_current:
        value_template: '{{ states.sensor.duet_status.attributes.temps.bed.current }}'
      bed_temp_active:
        value_template: '{{ states.sensor.duet_status.attributes.temps.bed.active }}'
      print_percentage:
        value_template: '{{ states.sensor.duet_status.attributes.fractionPrinted }}%'