homeassistant:
  customize:
    sensor.duet_status:
      friendly_name: '3D Printer Status'
      icon: mdi:printer-3d

sensor:
  - platform: rest
    name: Duet Status
    resource: http://taranis:1880/duet3d
    value_template: '{{ value_json.status }}'
    json_attributes:
      - temps
      - fractionPrinted
  - platform: template
    sensors:
      head_temp_current:
        value_template: '{{ states.sensor.duet_status.attributes.temps.heads.current[0] }}'
      head_temp_active:
        value_template: '{{ states.sensor.duet_status.attributes.temps.heads.active[0] }}'
      bed_temp_current:
        value_template: '{{ states.sensor.duet_status.attributes.temps.bed.current }}'
      bed_temp_active:
        value_template: '{{ states.sensor.duet_status.attributes.temps.bed.active }}'
      print_percentage:
        value_template: '{{ states.sensor.duet_status.attributes.fractionPrinted }}%'

group:
  3dprinter:
    name: Artemis
    entities:
      - sensor.duet_status
      - sensor.head_temp_current
      - sensor.head_temp_active
      - sensor.bed_temp_current
      - sensor.bed_temp_active
      - sensor.print_percentage
  3dprintstats: