homeassistant:
  customize:
    sensor.duet_status:
      friendly_name: '3D Printer Status'
      icon: mdi:printer-3d

sensor:
  - platform: rest
    name: Duet Status
    resource: http://artemis/rr_status?type=1
    value_template: '{{ value_json.status }}'
    json_attributes:
      - temps
  - platform: template
    sensors:
      head_temp_current:
        value_template: '{{ states.sensor.duet_status.attributes.temps.heads.current[0] }}'
      head_temp_active:
        value_template: '{{ states.sensor.duet_status.attributes.temps.heads.active[0] }}'
      bed_temp_current:
        value_template: '{{ states.sensor.duet_status.attributes.temps.bed.current }}'
      bed_temp_active:
        value_template: '{{ states.sensor.duet_status.attributes.temps.bed.active }}'

group:
  3dprinter:
    name: Artemis
    view: no
    entities:
      - sensor.duet_status
      - sensor.head_temp_current
      - sensor.head_temp_active
      - sensor.bed_temp_current
      - sensor.bed_temp_active