homeassistant:
  customize:
  # Control Panel
    script.home_control:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 7
        row_height: 75px
        column_width: 62px
        gap: 15px
        color: '#555B65'
        color_on: '#00CC33'
        #color_on: 'var(--primary-color)'
        #color_on: '#262B38'
        color_off: '#BBBEC2'
        entities:
          # lights
          - entity: light.master_bedroom
            icon: mdi:lightbulb
            label: M
            column: 1
            row: 1
          - entity: light.kids_rooms
            icon: mdi:lightbulb
            label: Kids
            column: 2
            row: 1

          - entity: light.back_room
            icon: mdi:lightbulb
            label: "Back"
            column: 5
            row: 1
          - entity: light.office
            icon: mdi:castle
            column: 6
            row: 1
          
          #row 4
          - entity: automation.michaels_alarm
            icon: mdi:alarm
            column: 1
            row: 2
          - entity: sensor.ups_status
            icon: mdi:battery-charging
            column: 3
            row: 2
          - entity: sensor.home
            icon: mdi:home
            label_state: sensor.home
            column: 6
            row: 2
    script.device_tiles:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 7
        row_height: 75px
        column_width: 62px
        gap: 15px
        color: '#555B65'
        color_on: '#00CC33'
        #color_on: 'var(--primary-color)'
        #color_on: '#262B38'
        color_off: '#BBBEC2'
        entities:
          - entity: sensor.taranis
            icon: mdi:linux
            column: 1
            row: 1
          - entity: sensor.camulos
            icon: mdi:windows
            column: 2
            row: 1

          - entity: sensor.xboxone
            icon: mdi:xbox
            column: 4
            row: 1
          - entity: sensor.nintendoswitch
            icon: mdi:nintendo-switch
            column: 5
            row: 1
          - entity: sensor.wii
            icon: mdi:wii
            column: 6
            row: 1 
    script.people_tiles:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 6
        row_height: 54px
        column_width: 62px
        gap: 8px
        color: 'hsl(192, 96%, 48%)'
        entities:
          - entity: device_tracker.goibniu_goibniu
            icon: mdi:human-male
            label_state: device_tracker.goibniu_goibniu
            column: 1
            column_span: 3
            row: 1
            row_span: 2
            color: 'hsl(0, 100%, 100%)'
            color_on: 'hsl(0, 100%, 100%)'
            color_off: 'hsl(0, 100%, 100%)'
            text_size: '1.2em'
            label_sec_state: sensor.battery_goibniu
            text_sec_color: "#eee"
            text_sec_size: '0.7em'
            more_info: device_tracker.goibniu_goibniu

          - entity: device_tracker.android1b27fe99b8b39bc3
            icon: mdi:human-female
            column: 4
            column_span: 3
            row: 1
            row_span: 2
            color: 'hsl(0, 100%, 100%)'
            color_on: 'hsl(0, 100%, 100%)'
            color_off: 'hsl(0, 100%, 100%)'
            text_size: '1.2em'
            label_sec_state: "Mary"
            text_sec_color: "#eee"
            text_sec_size: '0.7em'
            more_info: device_tracker.android1b27fe99b8b39bc3

script:
  home_control:
    sequence:
  device_tiles:
    sequence:
  people_tiles:
    sequence:

group:
  default_view:
    name: Default
    icon: mdi:home
    view: yes
    entities:
      - group.people_tiles
      - group.home_control
      - group.device_tiles

  home_control:
    name: Control Panel
    entities:
      - script.home_control
  device_tiles:
    name: Devices
    icon: mdi:owl
    entities:
      - script.device_tiles
  people_tiles:
    name: People
    icon: mdi:human-handsup
    entities:
      - script.people_tiles