homeassistant:
  customize:
  # Control Panel
    script.home_control:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 7
        row_height: 75px
        gap: 15px
        color: '#555B65'
        color_on: '#00CC33'
        #color_on: 'var(--primary-color)'
        #color_on: '#262B38'
        color_off: '#BBBEC2'
        entities:        
          #row 4
          - entity: automation.michaels_alarm
            icon: mdi:alarm
            column: 1
            row: 2
          - entity: sensor.ups_status
            icon: mdi:battery-charging
            column: 3
            row: 2
          - entity: sensor.home
            icon: mdi:home
            label_state: sensor.home
            column: 6
            row: 2
    script.device_tiles:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 7
        row_height: 75px
        gap: 15px
        color: '#555B65'
        color_on: '#00CC33'
        #color_on: 'var(--primary-color)'
        #color_on: '#262B38'
        color_off: '#BBBEC2'
        entities:
          - entity: sensor.taranis
            icon: mdi:linux
            column: 1
            row: 1
          - entity: sensor.camulos
            icon: mdi:windows
            column: 2
            row: 1

          - entity: sensor.xboxone
            icon: mdi:xbox
            column: 4
            row: 1
          - entity: sensor.nintendoswitch
            icon: mdi:nintendo-switch
            column: 5
            row: 1
          - entity: sensor.wii
            icon: mdi:wii
            column: 6
            row: 1 
    script.people_tiles:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 6
        row_height: 54px
        gap: 8px
        color: 'hsl(192, 96%, 48%)'
        entities:
          - entity: device_tracker.goibniu_goibniu
            image: !secret mike_profile_pic
            label_state: device_tracker.goibniu_goibniu
            column: 1
            column_span: 3
            row: 1
            row_span: 2
            color: 'hsl(0, 100%, 100%)'
            color_on: 'hsl(0, 100%, 100%)'
            color_off: 'hsl(0, 100%, 100%)'
            text_size: '1.2em'
            label_sec_state: sensor.battery_goibniu
            text_sec_color: "#eee"
            text_sec_size: '0.7em'
            more_info: device_tracker.goibniu_goibniu

          - entity: device_tracker.android1b27fe99b8b39bc3
            image: !secret mary_profile_pic
            column: 4
            column_span: 3
            row: 1
            row_span: 2
            color: 'hsl(0, 100%, 100%)'
            color_on: 'hsl(0, 100%, 100%)'
            color_off: 'hsl(0, 100%, 100%)'
            text_size: '1.2em'
            label_sec_state: "Mary"
            text_sec_color: "#eee"
            text_sec_size: '0.7em'
            more_info: device_tracker.android1b27fe99b8b39bc3

          - entity: light.back_room
            label: Back Room
            icon: mdi:lightbulb-outline
            column: 1              
            column_span: 3         
            row: 3             
            row_span: 1          
            color: 'hsl(192, 96%, 48%)'    #blue
            color_on: 'hsl(37, 96%, 48%)'  #orange
            color_off: 'hsl(192, 96%, 48%)'    #blue     
            #secondary label
            label_sec_template: "return state_time;"
            text_sec_color: "#eee"
            text_sec_size: '0.7em'
            icon_size: 18px

          - entity: light.kitchen
            label: Kitchen
            icon: mdi:lightbulb-outline
            column: 4         
            column_span: 3     
            row: 3              
            row_span: 1
            color: 'hsl(192, 96%, 48%)'    #blue
            color_on: 'hsl(37, 96%, 48%)'  #orange
            color_off: 'hsl(192, 96%, 48%)'    #blue 
            #secondary label
            label_sec_template: "return entities['light.kitchen'].attributes.status;"
            text_sec_color: "#eee"
            text_sec_size: '0.7em'
            text_sec_align: right  

          - entity: light.master_bedroom
            label: Master
            icon: mdi:lightbulb-outline  
            more_info: light.master_bedroom
            column: 1              
            column_span: 2      
            row: 4      
            row_span: 1         
            color: 'hsl(0, 0%, 80%)'    #grey        
            color_on: 'hsl(37, 96%, 48%)'  #orange
            color_off: 'hsl(0, 0%, 80%)'    #grey 
            icon_size: 18px
            label_sec_template: "return state_time;"
            text_sec_color: "#eee"
            text_sec_size: '0.7em'

          - entity: light.kids_room
            label: Kids Rooms
            icon: mdi:lightbulb-outline
            column: 3              
            column_span: 2        
            row: 4             
            row_span: 1          
            color: 'hsl(0, 0%, 80%)'    #grey        
            color_on: 'hsl(37, 96%, 48%)'  #orange
            color_off: 'hsl(0, 0%, 80%)'    #grey 
            icon_size: 18px  
            label_sec_template: "return state_time;"
            text_sec_color: "#eee"
            text_sec_size: '0.7em'  

          - entity: light.office
            label: Office
            icon: mdi:lightbulb-outline
            column: 5              
            column_span: 2        
            row: 4            
            row_span: 1      
            color: 'hsl(0, 0%, 80%)'    #grey        
            color_on: 'hsl(37, 96%, 48%)'  #orange
            color_off: 'hsl(0, 0%, 80%)'    #grey  
            icon_size: 18px
            label_sec_template: "return state_time;"
            text_sec_color: "#eee"
            text_sec_size: '0.7em'


    input_text.weather_information_tiles:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 6           
        row_height: 35px      
        gap: 0px              
        color: 'hsl(192, 96%, 48%)'
        text_size: '0.85em'
        entities:
          - entity: sensor.dark_sky_daily_high_temperature
            label_template: "return parseInt(state) + 'ºF'"
            icon: mdi:thermometer
            #more_info: history_graph.temperature
            column: 1
            column_span: 2
            row: 1            
            row_span: 1          
            color: 'hsla(0, 0%, 98%, 0)'    #whitetransparent
            color_on: 'hsla(0, 0%, 98%, 0)'    #whitetransparent
            color_off: 'hsla(0, 0%, 98%, 0)'    #whitetransparent
            text_color: 'hsl(0, 0%, 0%)'    #black
            text_color_on: 'hsl(0, 0%, 0%)'    #black
            text_color_off: 'hsl(0, 0%, 0%)'    #black
            icon_size: 12px

          - entity: sensor.dark_sky_precip_probability
            label_template: "return parseInt(state) + '%'"
            icon: mdi:weather-rainy
            #more_info: history_graph.humidity
            column: 3
            column_span: 2
            row: 1              
            row_span: 1          
            color: 'hsla(0, 0%, 98%, 0)'    #whitetransparent
            color_on: 'hsla(0, 0%, 98%, 0)'    #whitetransparent
            color_off: 'hsla(0, 0%, 98%, 0)'    #whitetransparent
            text_color: 'hsl(0, 0%, 0%)'    #black
            text_color_on: 'hsl(0, 0%, 0%)'    #black
            text_color_off: 'hsl(0, 0%, 0%)'    #black
            icon_size: 12px

          - entity: sensor.dark_sky_wind_speed
            label_template: "return parseFloat(state) + 'MPH'"
            icon: mdi:weather-windy
            #more_info: history_graph.brightness
            column: 5
            column_span: 2
            row: 1             
            row_span: 1          
            color: 'hsla(0, 0%, 98%, 0)'    #whitetransparent
            color_on: 'hsla(0, 0%, 98%, 0)'    #whitetransparent
            color_off: 'hsla(0, 0%, 98%, 0)'    #whitetransparent
            text_color: 'hsl(0, 0%, 0%)'    #black
            text_color_on: 'hsl(0, 0%, 0%)'    #black
            text_color_off: 'hsl(0, 0%, 0%)'    #black
            icon_size: 12px

          - entity: sensor.dark_sky_daily_summary
            label_state: sensor.dark_sky_daily_summary
            #icon_template: "return 'mdi:' + entities['sensor.weather_icon'].state;"
            label_sec_template: "return parseInt(entities['sensor.dark_sky_daily_low_temperature'].state) + 'ºF to ' + parseInt(entities['sensor.dark_sky_daily_high_temperature'].state) + 'ºF'"
            column: 1
            column_span: 6
            row: 2            
            row_span: 3          
            color: 'hsla(0, 0%, 98%, 0)'    #whitetransparent
            color_on: 'hsla(0, 0%, 98%, 0)'    #whitetransparent
            color_off: 'hsla(0, 0%, 98%, 0)'    #whitetransparent
            text_color: 'hsl(0, 0%, 0%)'    #black
            text_color_on: 'hsl(0, 0%, 0%)'    #black
            text_color_off: 'hsl(0, 0%, 0%)'    #black
            text_sec_color: 'hsl(0, 0%, 0%)'    #black
            icon_size: 12px

    input_text.dummy_tiles_security:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 6           
        row_height: 54px      
        gap: 8px              
        entities:
          - entity: cover.garage_door
            label: "Garage"
            icon: mdi:garage
            more_info: cover.garage_door
            column: 1              
            column_span: 6     
            row: 2            
            row_span: 1  
            color: 'hsl(0, 0%, 80%)'    #grey        
            color_on: 'hsl(37, 96%, 48%)'  #orange
            color_off: 'hsl(0, 0%, 80%)'    #gr
            label_sec_template: "return state + ' for ' + state_time;"
            text_sec_color: "#eee"
            text_sec_size: '0.7em'

input_text:
  dummy_tiles_security:
    name: Security
  weather_information_tiles:
    name: Weather

script:
  home_control:
    sequence:
  device_tiles:
    sequence:
  people_tiles:
    sequence:
  weather_information_tiles:
    sequence:

group:
  default_view:
    name: Default
    icon: mdi:home
    view: yes
    entities:
      - group.people_tiles
      - group.home_control
      - group.device_tiles

  home_control:
    name: Control Panel
    entities:
      - script.home_control
  device_tiles:
    name: Devices
    icon: mdi:owl
    entities:
      - script.device_tiles
  people_tiles:
    name: People
    icon: mdi:human-handsup
    entities:
      - script.people_tiles
      - input_text.weather_information_tiles
      - input_text.dummy_tiles_security