binary_sensor:
  - platform: mqtt
    name: "Camulos - Connected"
    state_topic: "iotlink/wiredbyte/camulos/lwt"
    value_template: "{{ value }}"
    payload_on: "ON"
    payload_off: "OFF"
    device_class: "connectivity"
    qos: 1

sensor:

  - platform: mqtt
    name: "Camulos - Current User"
    state_topic: "iotlink/wiredbyte/camulos/windows-monitor/stats/system/current-user"
    unit_of_measurement: ''
    icon: mdi:account
    value_template: "{{ value }}"
    availability_topic: "iotlink/wiredbyte/camulos/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Camulos - Idle Time"
    state_topic: "iotlink/wiredbyte/camulos/windows-monitor/stats/system/idle-time"
    unit_of_measurement: 'seconds'
    icon: mdi:timer
    value_template: "{{ value }}"
    availability_topic: "iotlink/wiredbyte/camulos/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Camulos - CPU Usage"
    state_topic: "iotlink/wiredbyte/camulos/windows-monitor/stats/cpu/usage"
    unit_of_measurement: '%'
    icon: mdi:speedometer
    value_template: "{{ value }}"
    availability_topic: "iotlink/wiredbyte/camulos/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Camulos - RAM Usage"
    state_topic: "iotlink/wiredbyte/camulos/windows-monitor/stats/memory/usage"
    unit_of_measurement: '%'
    icon: mdi:memory
    value_template: "{{ value }}"
    availability_topic: "iotlink/wiredbyte/camulos/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Camulos - RAM Available"
    state_topic: "iotlink/wiredbyte/camulos/windows-monitor/stats/memory/available"
    unit_of_measurement: 'MB'
    icon: mdi:memory
    value_template: "{{ value }}"
    availability_topic: "iotlink/wiredbyte/camulos/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Camulos - RAM Used"
    state_topic: "iotlink/wiredbyte/camulos/windows-monitor/stats/memory/used"
    unit_of_measurement: 'MB'
    icon: mdi:memory
    value_template: "{{ value }}"
    availability_topic: "iotlink/wiredbyte/camulos/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Camulos - RAM Total"
    state_topic: "iotlink/wiredbyte/camulos/windows-monitor/stats/memory/total"
    unit_of_measurement: 'MB'
    icon: mdi:memory
    value_template: "{{ value }}"
    availability_topic: "iotlink/wiredbyte/camulos/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Camulos - HDD Usage (C)"
    state_topic: "iotlink/wiredbyte/camulos/windows-monitor/stats/hard-drive/c/drive-usage"
    unit_of_measurement: '%'
    icon: mdi:chart-donut
    value_template: "{{ value }}"
    availability_topic: "iotlink/wiredbyte/camulos/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Camulos - HDD Total Size (C)"
    state_topic: "iotlink/wiredbyte/camulos/windows-monitor/stats/hard-drive/c/total-size"
    unit_of_measurement: 'GB'
    icon: mdi:harddisk
    value_template: "{{ value }}"
    availability_topic: "iotlink/wiredbyte/camulos/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Camulos - HDD Total Free Space (C)"
    state_topic: "iotlink/wiredbyte/camulos/windows-monitor/stats/hard-drive/c/total-free-space"
    unit_of_measurement: 'GB'
    icon: mdi:harddisk
    value_template: "{{ value }}"
    availability_topic: "iotlink/wiredbyte/camulos/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Camulos - HDD Free Space (C)"
    state_topic: "iotlink/wiredbyte/camulos/windows-monitor/stats/hard-drive/c/available-free-space"
    unit_of_measurement: 'GB'
    icon: mdi:harddisk
    value_template: "{{ value }}"
    availability_topic: "iotlink/wiredbyte/camulos/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Camulos - HDD Used Space (C)"
    state_topic: "iotlink/wiredbyte/camulos/windows-monitor/stats/hard-drive/c/used-space"
    unit_of_measurement: 'GB'
    icon: mdi:harddisk
    value_template: "{{ value }}"
    availability_topic: "iotlink/wiredbyte/camulos/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Camulos - HDD Format (C)"
    state_topic: "iotlink/wiredbyte/camulos/windows-monitor/stats/hard-drive/c/drive-format"
    unit_of_measurement: ''
    icon: mdi:harddisk
    value_template: "{{ value }}"
    availability_topic: "iotlink/wiredbyte/camulos/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Camulos - HDD Label (C)"
    state_topic: "iotlink/wiredbyte/camulos/windows-monitor/stats/hard-drive/c/volume-label"
    unit_of_measurement: ''
    icon: mdi:harddisk
    value_template: "{{ value }}"
    availability_topic: "iotlink/wiredbyte/camulos/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Camulos - Network IPv4"
    state_topic: "iotlink/wiredbyte/camulos/windows-monitor/stats/network/0/ipv4"
    unit_of_measurement: ''
    icon: mdi:lan
    value_template: "{{ value }}"
    availability_topic: "iotlink/wiredbyte/camulos/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Camulos - Network IPv6"
    state_topic: "iotlink/wiredbyte/camulos/windows-monitor/stats/network/0/ipv6"
    unit_of_measurement: ''
    icon: mdi:lan
    value_template: "{{ value }}"
    availability_topic: "iotlink/wiredbyte/camulos/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Camulos - Network Speed"
    state_topic: "iotlink/wiredbyte/camulos/windows-monitor/stats/network/0/speed"
    unit_of_measurement: 'Mbps'
    icon: mdi:speedometer
    value_template: "{{ value }}"
    availability_topic: "iotlink/wiredbyte/camulos/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Camulos - Network Wired"
    state_topic: "iotlink/wiredbyte/camulos/windows-monitor/stats/network/0/wired"
    unit_of_measurement: ''
    icon: mdi:ethernet
    value_template: "{{ value }}"
    availability_topic: "iotlink/wiredbyte/camulos/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

camera:
  - platform: mqtt
    name: "Camulos - Screen 0"
    topic: "iotlink/wiredbyte/camulos/windows-monitor/stats/display/0/screen"

switch:
  - platform: template
    switches:
      camulos:
        friendly_name: "Camulos"
        value_template: "{{ is_state('binary_sensor.camulos_connected', 'on') }}"
        turn_on:
          service: script.camulos_wake
        turn_off:
          service: script.camulos_shutdown
        icon_template: mdi:laptop

script:
  camulos_wake:
    # To enable see https://www.home-assistant.io/components/wake_on_lan/
    alias: "Camulos - Wake"
    sequence:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: "70:85:C2:63:9F:11"

  camulos_shutdown:
    alias: "Camulos - Shutdown"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/wiredbyte/camulos/commands/shutdown"
          payload: ""

  camulos_suspend:
    alias: "Camulos - Suspend"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/wiredbyte/camulos/commands/suspend"
          payload: ""

  camulos_hibernate:
    alias: "Camulos - Hibernate"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/wiredbyte/camulos/commands/hibernate"
          payload: ""

  camulos_reboot:
    alias: "Camulos - Reboot"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/wiredbyte/camulos/commands/reboot"
          payload: ""

  camulos_lock:
    alias: "Camulos - Lock"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/wiredbyte/camulos/commands/lock"
          payload: ""

  camulos_logoff:
    alias: "Camulos - Logoff"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/wiredbyte/camulos/commands/logoff"
          payload: ""

  camulos_vol_mute:
    alias: "Camulos - Toggle Mute"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/wiredbyte/camulos/commands/volume/mute"
          payload: ""

  camulos_vol_max:
    alias: "Camulos - Vol Max"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/wiredbyte/camulos/commands/volume/set"
          payload: "100"

  camulos_displays_on:
    alias: "Camulos - Displays ON"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/wiredbyte/camulos/commands/displays/on"
          payload: ""

  camulos_displays_off:
    alias: "Camulos - Displays OFF"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/wiredbyte/camulos/commands/displays/off"
          payload: ""

  camulos_refresh:
    alias: "Camulos - Refresh"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/wiredbyte/camulos/refresh"
          payload: ""

  camulos_notify:
    alias: "Camulos - Notify"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/wiredbyte/camulos/commands/notify"
          payload: '{ "title": "My Notification Title", "message": "This is an example of notification using IOT Link", "launchParams": "toast://open/https://iotlink.gitlab.io" }'

  camulos_set_hue_color:
    alias: "Camulos - Set Hue Color"
    variables:
      pc_color: ff0000
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/wiredbyte/camulos/commands/run"
          payload: '{ "command": "C:\\liquidctl-1.4.1-bin-windows-x86_64\\liquidctl.exe", "args": "set led1 color breathing {{ pc_color }}", "path": "", "user": "", "visible": true, "fallback": true }'
