homeassistant:
  customize:
    alarm_control_panel.house:
      custom_ui_state_card: state-card-custom-ui
      state_card_custom_ui_secondary: state-card-custom_alarm
      
alarm_control_panel:
  - platform: manual_mqtt
    name: House
    state_topic: home/alarm
    command_topic: home/alarm/set

automation:
  - id: alarm_arm_away
    alias: 'Arm alarm when no one home'
    trigger:
      platform: state
      entity_id: group.people
      to: 'not_home'
      for:
        minutes: 5
    action:
      - service: notify.slack
        data:
          message: 'Arming Alarm - no one is home.'
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.house
  - id: alarm_disarm_home
    alias: 'Disarm alarm when someone is home'
    trigger:
      platform: state
      entity_id: group.people
      to: 'home'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: 'pending'
        - condition: state
          entity_id: alarm_control_panel.house
          state: 'armed_away'
    action:
      - service: notify.slack
        data:
          message: 'Disarming Alarm - Someone is home'
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.house
  - id: alarm_trigger_away
    alias: 'Trigger alarm while armed away'
    trigger:
      - platform: state
        entity_id: cover.garage_door
        to: 'open'
      # Light for testing
      - platform: state
        entity_id: light.office
        to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.house
        state: armed_away
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.house
      - service: persistent_notification.create
        data_template:
          message: "Alarm was triggered at {{ as_timestamp(trigger.to_state.last_changed) | timestamp_custom('%D %-I:%M %P') }}!"
          title: "Alarm Triggered!"

alert:
  alarm:
    name: ":rotating_light: Alarm was triggered at {{ as_timestamp(states.alarm_control_panel.house.last_changed) | timestamp_custom('%D %-I:%M %P') }}!"
    entity_id: alarm_control_panel.house
    state: 'triggered'
    repeat: 5
    can_acknowledge: true
    notifiers:
      - slack

group:
  alarm_panel:
    name: Control
    view: no
    entities:
      - alarm_control_panel.house