homeassistant:
  customize:
    sensor.download_speed_mean:
      friendly_name: 'SNMP Download Average'
      icon: mdi:speedometer
    sensor.upload_speed_mean:
      friendly_name: 'SNMP Upload Average'
      icon: mdi:speedometer
    sensor.ping_time_mean:
      friendly_name: 'SNMP Ping Average'
      icon: mdi:clock-fast
    sensor.wan_traffic_in_mean:
      friendly_name: 'WAN Download Average'
      icon: mdi:download
    sensor.wan_traffic_out_mean:
      friendly_name: 'WAN Upload Average'
      icon: mdi:upload

sensor:
  - platform: snmp
    name: snmp_wan_in
    host: !secret router_ip
    baseoid: 1.3.6.1.2.1.2.2.1.10.6

  - platform: snmp
    name: snmp_wan_out
    host: !secret router_ip
    baseoid: 1.3.6.1.2.1.2.2.1.16.6

  - platform: snmp
    name: snmp_wan_port_speed
    host: !secret router_ip
    baseoid: 1.3.6.1.2.1.2.2.1.5.6

  - platform: template
    sensors:
        internet_speed_in:
          friendly_name: 'Internet Speed IN'
          value_template: '{{ ((states.input_number.internet_traffic_delta_in.state | float ) / 1000000 ) | round(2) }}'
          unit_of_measurement: 'Mbps'

  - platform: template
    sensors:
        internet_speed_out:
          friendly_name: 'Internet Speed OUT'
          value_template: '{{ ((states.input_number.internet_traffic_delta_out.state | float ) / 1000000 ) | round(2) }}'
          unit_of_measurement: 'Mbps'

  - platform: template
    sensors:
        wan_port_speed:
          friendly_name: 'WAN Port Speed'
          value_template: '{{ (( states.sensor.snmp_wan_port_speed.state | float) / 1000000 ) | round(0) }}'
          unit_of_measurement: 'Mbps'

  - platform: statistics
    name: 'WAN Traffic In'
    entity_id: sensor.internet_speed_in

  - platform: statistics
    name: 'WAN Traffic Out'
    entity_id: sensor.internet_speed_out

input_number:
  internet_traffic_delta_in:
    name: "Traffic IN Delta"
    initial: 0
    min: 0
    max: 1000000000000

  internet_traffic_delta_out:
    name: "Traffic OUT Delta"
    initial: 0
    min: 0
    max: 1000000000000

automation:
  - id: snmp_monitor_traffic_in
    alias: Monitor Traffic In
    trigger:
      platform: state
      entity_id: sensor.snmp_wan_in
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.internet_traffic_delta_in
          value: '{{ ((trigger.to_state.state | int - trigger.from_state.state | int) * 8 ) / ( as_timestamp(trigger.to_state.last_updated) - as_timestamp(trigger.from_state.last_updated) ) }}'
  
  - id: snmp_monitor_traffic_out
    alias: Monitor Traffic Out
    trigger:
      platform: state
      entity_id: sensor.snmp_wan_out
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.internet_traffic_delta_out
          value: '{{ ((trigger.to_state.state | int - trigger.from_state.state | int) * 8 ) / ( as_timestamp(trigger.to_state.last_updated) - as_timestamp(trigger.from_state.last_updated) ) }}'

group:
  snmp_monitor:
    name: Bandwith Monitoring
    entities:
      - sensor.internet_speed_in
      - sensor.internet_speed_out
      - sensor.wan_traffic_in_mean
      - sensor.wan_traffic_out_mean
  snmp_raw_values:
    name: SNMP Raw Values
    entities:
      - sensor.snmp_wan_in
      - sensor.snmp_wan_out