sensor:
  # AP information - from https://community.home-assistant.io/t/system-monitoring-how-does-your-look/109713/421
  - platform: snmp
    name: 'AP Model'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.3.3.0
  - platform: snmp
    name: 'AP Firmware'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.3.6.0
  - platform: snmp
    name: 'AP Memory Total'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.10002.1.1.1.1.1.0
  - platform: snmp
    name: 'AP Memory Free'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.10002.1.1.1.1.2.0
  - platform: snmp
    name: 'AP CPU Load 1'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.10002.1.1.1.4.2.1.3.1
  - platform: snmp
    name: 'AP CPU Load 5'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.10002.1.1.1.4.2.1.3.2
  - platform: snmp
    name: 'AP CPU Load 10'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.10002.1.1.1.4.2.1.3.3
  - platform: snmp
    name: 'AP Uptime Raw'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.3.5.0
    # VAP Stats
  - platform: snmp
    name: 'VAP 1 Channel'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.4.1
    unit_of_measurement: "channel"
  - platform: snmp
    name: 'VAP 2 Channel'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.4.2
    unit_of_measurement: "channel"
  - platform: snmp
    name: 'VAP 3 Channel'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.4.3
    unit_of_measurement: "channel"
  - platform: snmp
    name: 'VAP 4 Channel'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.4.4
    unit_of_measurement: "channel"
  - platform: snmp
    name: 'VAP 5 Channel'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.4.5
    unit_of_measurement: "channel"
  - platform: snmp
    name: 'VAP 6 Channel'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.4.6
    unit_of_measurement: "channel"
  - platform: snmp
    name: 'VAP 7 Channel'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.4.7
    unit_of_measurement: "channel"
  - platform: snmp
    name: 'VAP 8 Channel'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.4.8
    unit_of_measurement: "channel"
  - platform: snmp
    name: 'VAP 9 Channel'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.4.9
    unit_of_measurement: "channel"
  - platform: snmp
    name: 'VAP 10 Channel'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.4.10
    unit_of_measurement: "channel"
    
  - platform: snmp
    name: 'VAP 1 ESS'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.6.1
  - platform: snmp
    name: 'VAP 2 ESS'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.6.2
  - platform: snmp
    name: 'VAP 3 ESS'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.6.3
  - platform: snmp
    name: 'VAP 4 ESS'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.6.4
  - platform: snmp
    name: 'VAP 5 ESS'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.6.5
  - platform: snmp
    name: 'VAP 6 ESS'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.6.6
  - platform: snmp
    name: 'VAP 7 ESS'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.6.7
  - platform: snmp
    name: 'VAP 8 ESS'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.6.8
  - platform: snmp
    name: 'VAP 9 ESS'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.6.9
  - platform: snmp
    name: 'VAP 10 ESS'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.6.10

  - platform: snmp  
    name: 'VAP 1 Clients'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.8.1
    unit_of_measurement: "clients"
  - platform: snmp
    name: 'VAP 2 Clients'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.8.2
    unit_of_measurement: "clients"
  - platform: snmp
    name: 'VAP 3 Clients'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.8.3
    unit_of_measurement: "clients"
  - platform: snmp
    name: 'VAP 4 Clients'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.8.4
    unit_of_measurement: "clients"
  - platform: snmp
    name: 'VAP 5 Clients'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.8.5
    unit_of_measurement: "clients"
  - platform: snmp
    name: 'VAP 6 Clients'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.8.6
    unit_of_measurement: "clients"
  - platform: snmp
    name: 'VAP 7 Clients'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.8.7
    unit_of_measurement: "clients"
  - platform: snmp
    name: 'VAP 8 Clients'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.8.8
    unit_of_measurement: "clients"
  - platform: snmp
    name: 'VAP 9 Clients'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.8.9
    unit_of_measurement: "clients"
  - platform: snmp
    name: 'VAP 10 Clients'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.8.10
    unit_of_measurement: "clients"

  - platform: snmp  
    name: 'VAP 1 Radio'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.9.1
  - platform: snmp
    name: 'VAP 2 Radio'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.9.2
  - platform: snmp
    name: 'VAP 3 Radio'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.9.3
  - platform: snmp
    name: 'VAP 4 Radio'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.9.4
  - platform: snmp
    name: 'VAP 5 Radio'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.9.5
  - platform: snmp
    name: 'VAP 6 Radio'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.9.6
  - platform: snmp
    name: 'VAP 7 Radio'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.9.7
  - platform: snmp
    name: 'VAP 8 Radio'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.9.8
  - platform: snmp
    name: 'VAP 9 Radio'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.9.9
  - platform: snmp
    name: 'VAP 10 Radio'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.9.10

  - platform: snmp  
    name: 'VAP 1 RX Bytes'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.10.1
    unit_of_measurement: "bytes"
  - platform: snmp
    name: 'VAP 2 RX Bytes'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.10.2
    unit_of_measurement: "bytes"
  - platform: snmp
    name: 'VAP 3 RX Bytes'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.10.3
    unit_of_measurement: "bytes"
  - platform: snmp
    name: 'VAP 4 RX Bytes'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.10.4
    unit_of_measurement: "bytes"
  - platform: snmp
    name: 'VAP 5 RX Bytes'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.10.5
    unit_of_measurement: "bytes"
  - platform: snmp
    name: 'VAP 6 RX Bytes'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.10.6
    unit_of_measurement: "bytes"
  - platform: snmp
    name: 'VAP 7 RX Bytes'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.10.7
    unit_of_measurement: "bytes"
  - platform: snmp
    name: 'VAP 8 RX Bytes'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.10.8
    unit_of_measurement: "bytes"
  - platform: snmp
    name: 'VAP 9 RX Bytes'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.10.9
    unit_of_measurement: "bytes"
  - platform: snmp
    name: 'VAP 10 RX Bytes'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.10.10
    unit_of_measurement: "bytes"

  - platform: snmp  
    name: 'VAP 1 TX Bytes'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.16.1
    unit_of_measurement: "bytes"
  - platform: snmp
    name: 'VAP 2 TX Bytes'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.16.2
    unit_of_measurement: "bytes"
  - platform: snmp
    name: 'VAP 3 TX Bytes'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.16.3
    unit_of_measurement: "bytes"
  - platform: snmp
    name: 'VAP 4 TX Bytes'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.16.4
    unit_of_measurement: "bytes"
  - platform: snmp
    name: 'VAP 5 TX Bytes'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.16.5
    unit_of_measurement: "bytes"
  - platform: snmp
    name: 'VAP 6 TX Bytes'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.16.6
    unit_of_measurement: "bytes"
  - platform: snmp
    name: 'VAP 7 TX Bytes'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.16.7
    unit_of_measurement: "bytes"
  - platform: snmp
    name: 'VAP 8 TX Bytes'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.16.8
    unit_of_measurement: "bytes"
  - platform: snmp
    name: 'VAP 9 TX Bytes'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.16.9
    unit_of_measurement: "bytes"
  - platform: snmp
    name: 'VAP 10 TX Bytes'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.1.2.1.16.10
    unit_of_measurement: "bytes"

    # Conversions
  - platform: template
    sensors:
      ap_uptime_conv:
        value_template: >-
          {% set time = (states('sensor.ap_uptime_raw') | int) | int %}
          {% set minutes = ((time % 3600) / 60) | int%}
          {% set hours = ((time % 86400) / 3600) | int %}
          {% set days = (time / 86400) | int %}
            {%- if time < 60 -%}
              < 1 min
              {%- else -%}
              {{ days }}:{{ hours }}:{{ minutes }}
            {%- endif -%}
      ap_memory_percent:
        value_template: >-
          {{ ((states('sensor.ap_memory_free') | int  / states('sensor.ap_memory_total') | int ) * 100 ) | round(0) }}
