sensor:
  # AP information - from https://community.home-assistant.io/t/system-monitoring-how-does-your-look/109713/421
  - platform: snmp
    name: 'AP Model'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.3.3.0
  - platform: snmp
    name: 'AP Firmware'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.3.6.0
  - platform: snmp
    name: 'AP Memory Total'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.10002.1.1.1.1.1.0
  - platform: snmp
    name: 'AP Memory Free'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.10002.1.1.1.1.2.0
  - platform: snmp
    name: 'AP CPU Load 1'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.10002.1.1.1.4.2.1.3.1
  - platform: snmp
    name: 'AP CPU Load 5'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.10002.1.1.1.4.2.1.3.2
  - platform: snmp
    name: 'AP CPU Load 10'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.10002.1.1.1.4.2.1.3.3
  - platform: snmp
    name: 'AP Uptime Raw'
    host: !secret ap_ip
    community: 'public'
    baseoid: 1.3.6.1.4.1.41112.1.6.3.5.0
    # Conversions
  - platform: template
    sensors:
      ap_uptime_conv:
        value_template: >-
          {% set time = (states('sensor.ap_uptime_raw') | int) | int %}
          {% set minutes = ((time % 3600) / 60) | int%}
          {% set hours = ((time % 86400) / 3600) | int %}
          {% set days = (time / 86400) | int %}
            {%- if time < 60 -%}
              < 1 min
              {%- else -%}
              {{ days }}:{{ hours }}:{{ minutes }}
            {%- endif -%}
      ap_memory_percent:
        value_template: >-
          {{ ((states('sensor.ap_memory_free') | int  / states('sensor.ap_memory_total') | int ) * 100 ) | round(0) }}
