weather:
  - platform: darksky
    api_key: !secret forecast_api_key

sensor:
  - platform: darksky
    api_key: !secret forecast_api_key
    forecast:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    monitored_conditions:
      - summary
      - precip_type
      - precip_intensity
      - precip_probability
      - precip_accumulation
      - temperature
      - apparent_temperature
      - wind_gust
      - wind_speed
      - wind_bearing
      - humidity
      - icon
      - pressure
      - temperature_low
      - temperature_high
      - daily_summary
      - alerts
  - platform: airvisual
    api_key: !secret airvisual_api_key
    monitored_conditions:
      - us
  - platform: season
  - platform: template
    sensors:
      weekday:
        friendly_name: 'Weekday'
        value_template: '{{ now().strftime("%A") }}'
        
  - platform: rest
    resource: https://api.weather.gov/alerts/active/count
    name: NWS Alert Count
    value_template: >
      {% if value_json.zones.WAZ673 is defined %}
        {{ value_json.zones.WAZ673 }}
      {% else %}
        0
      {% endif %}
    headers:
      User-Agent: Homeassistant
      Accept: application/ld+json
    scan_interval: 60
      
  - platform: rest
    resource: https://api.weather.gov/alerts/active?zone=WAZ673
    name: NWS Alert Event
    value_template: >
      {% if value_json.features[0] is defined %}
        {{ value_json['features'][0]['properties'].event }}
      {% else %}
        None
      {% endif %}