homeassistant:
  customize:
    group.weather_tab:
      order: 1

sensor:
  - platform: darksky
    api_key: !secret forecast_api_key
    forecast:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    monitored_conditions:
      - summary
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - apparent_temperature
      - wind_speed
      - wind_bearing
      - humidity
      - icon
      - pressure
      - temperature_min
      - temperature_max
      - daily_summary
  - platform: airvisual
    api_key: !secret airvisual_api_key
    monitored_conditions:
      - us
  - platform: season
  - platform: template
    sensors:
      weekday:
        friendly_name: 'Weekday'
        value_template: '{{ now().strftime("%A") }}'
      forecast_0:
        friendly_name: "Today's Forecast"
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability.state|round(0)}}%
        icon_template: >-
          {% if is_state("sensor.dark_sky_icon", "clear-day") %}
            mdi:weather-sunny
          {% elif is_state("sensor.dark_sky_icon", "clear-night") %}
            mdi:weather-night
          {% elif is_state("sensor.dark_sky_icon", "cloudy") %}
            mdi:weather-cloudy   
          {% elif is_state("sensor.dark_sky_icon", "rain") %}
            mdi:weather-pouring        
          {% elif is_state("sensor.dark_sky_icon", "sleet") %}
            mdi:weather-snowy-rain
          {% elif is_state("sensor.dark_sky_icon", "snow") %}
            mdi:weather-snowy
          {% elif is_state("sensor.dark_sky_icon", "wind") %}
            mdi:weather-windy
          {% elif is_state("sensor.dark_sky_icon", "fog") %}
            mdi:weather-fog
          {% elif is_state("sensor.dark_sky_icon", "partly-cloudy-day") %}
            mdi:weather-partlycloudy
          {% elif is_state("sensor.dark_sky_icon", "partly-cloudy-night") %}
            mdi:weather-partlycloudy            
          {% else %}
            error
          {% endif %}    
      forecast_1:
        friendly_name_template: '{{ (as_timestamp(now()) + (86400)) | timestamp_custom("%A", True) }}'
        value_template: >          
          {{states.sensor.dark_sky_daily_high_temperature_1.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_1.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_1.state|round(0)}}%
        icon_template: >-
          {% if is_state("sensor.forecast_first_icon", "clear-day") %}
            mdi:weather-sunny
          {% elif is_state("sensor.forecast_first_icon", "clear-night") %}
            mdi:weather-night
          {% elif is_state("sensor.forecast_first_icon", "cloudy") %}
            mdi:weather-cloudy   
          {% elif is_state("sensor.forecast_first_icon", "rain") %}
            mdi:weather-pouring        
          {% elif is_state("sensor.forecast_first_icon", "sleet") %}
            mdi:weather-snowy-rain
          {% elif is_state("sensor.forecast_first_icon", "snow") %}
            mdi:weather-snowy
          {% elif is_state("sensor.forecast_first_icon", "wind") %}
            mdi:weather-windy
          {% elif is_state("sensor.forecast_first_icon", "fog") %}
            mdi:weather-fog
          {% elif is_state("sensor.forecast_first_icon", "partly-cloudy-day") %}
            mdi:weather-partlycloudy
          {% elif is_state("sensor.forecast_first_icon", "partly-cloudy-night") %}
            mdi:weather-partlycloudy            
          {% else %}
            error
          {% endif %}
      forecast_first_icon:
        value_template: "{{states.sensor.dark_sky_icon_1.state}}"
    
      forecast_2:
        friendly_name_template: '{{ (as_timestamp(now()) + (86400) *2) | timestamp_custom("%A", True) }}'
        value_template: >          
          {{states.sensor.dark_sky_daily_high_temperature_2.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_2.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_2.state|round(0)}}%
        icon_template: >-
          {% if is_state("sensor.forecast_second_icon", "clear-day") %}
            mdi:weather-sunny
          {% elif is_state("sensor.forecast_second_icon", "clear-night") %}
            mdi:weather-night
          {% elif is_state("sensor.forecast_second_icon", "cloudy") %}
            mdi:weather-cloudy   
          {% elif is_state("sensor.forecast_second_icon", "rain") %}
            mdi:weather-pouring        
          {% elif is_state("sensor.forecast_second_icon", "sleet") %}
            mdi:weather-snowy-rain 
          {% elif is_state("sensor.forecast_second_icon", "snow") %}
            mdi:weather-snowy
          {% elif is_state("sensor.forecast_second_icon", "wind") %}
            mdi:weather-windy
          {% elif is_state("sensor.forecast_second_icon", "fog") %}
            mdi:weather-fog
          {% elif is_state("sensor.forecast_second_icon", "partly-cloudy-day") %}
            mdi:weather-partlycloudy
          {% elif is_state("sensor.forecast_second_icon", "partly-cloudy-night") %}
            mdi:weather-partlycloudy            
          {% else %}
            error
          {% endif %}
      forecast_second_icon:
        value_template: "{{states.sensor.dark_sky_icon_2.state}}"
                 
      forecast_3:
        friendly_name_template: '{{ (as_timestamp(now()) + (86400) *3) | timestamp_custom("%A", True) }}'
        value_template: >          
          {{states.sensor.dark_sky_daily_high_temperature_3.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_3.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_3.state|round(0)}}%
        icon_template: >-
          {% if is_state("sensor.forecast_third_icon", "clear-day") %}
            mdi:weather-sunny
          {% elif is_state("sensor.forecast_third_icon", "clear-night") %}
            mdi:weather-night
          {% elif is_state("sensor.forecast_third_icon", "cloudy") %}
            mdi:weather-cloudy   
          {% elif is_state("sensor.forecast_third_icon", "rain") %}
            mdi:weather-pouring        
          {% elif is_state("sensor.forecast_third_icon", "sleet") %}
            mdi:weather-snowy-rain 
          {% elif is_state("sensor.forecast_third_icon", "snow") %}
            mdi:weather-snowy
          {% elif is_state("sensor.forecast_third_icon", "wind") %}
            mdi:weather-windy
          {% elif is_state("sensor.forecast_third_icon", "fog") %}
            mdi:weather-fog
          {% elif is_state("sensor.forecast_third_icon", "partly-cloudy-day") %}
            mdi:weather-partlycloudy
          {% elif is_state("sensor.forecast_third_icon", "partly-cloudy-night") %}
            mdi:weather-partlycloudy
          {% else %}
            error
          {% endif %}
      forecast_third_icon:
        value_template: "{{states.sensor.dark_sky_icon_3.state}}"
        
      forecast_4:
        friendly_name_template: '{{ (as_timestamp(now()) + (86400) *4) | timestamp_custom("%A", True) }}'
        value_template: >          
          {{states.sensor.dark_sky_daily_high_temperature_4.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_4.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_4.state|round(0)}}%
        icon_template: >-
          {% if is_state("sensor.forecast_fourth_icon", "clear-day") %}
            mdi:weather-sunny
          {% elif is_state("sensor.forecast_fourth_icon", "clear-night") %}
            mdi:weather-night            
          {% elif is_state("sensor.forecast_fourth_icon", "cloudy") %}
            mdi:weather-cloudy   
          {% elif is_state("sensor.forecast_fourth_icon", "rain") %}
            mdi:weather-pouring        
          {% elif is_state("sensor.forecast_fourth_icon", "sleet") %}
            mdi:weather-snowy-rain 
          {% elif is_state("sensor.forecast_fourth_icon", "snow") %}
            mdi:weather-snowy
          {% elif is_state("sensor.forecast_fourth_icon", "wind") %}
            mdi:weather-windy
          {% elif is_state("sensor.forecast_fourth_icon", "fog") %}
            mdi:weather-fog
          {% elif is_state("sensor.forecast_fourth_icon", "partly-cloudy-day") %}
            mdi:weather-partlycloudy
          {% elif is_state("sensor.forecast_fourth_icon", "partly-cloudy-night") %}
            mdi:weather-partlycloudy
          {% else %}
            error
          {% endif %}
      forecast_fourth_icon:
        value_template: "{{states.sensor.dark_sky_icon_4.state}}"

      forecast_5:
        friendly_name_template: '{{ (as_timestamp(now()) + (86400) *5) | timestamp_custom("%A", True) }}'
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_5.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_5.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_5.state|round(0)}}%
        icon_template: >-
          {% if is_state("sensor.forecast_fifth_icon", "clear-day") %}
            mdi:weather-sunny
          {% elif is_state("sensor.forecast_fifth_icon", "clear-night") %}
            mdi:weather-night
          {% elif is_state("sensor.forecast_fifth_icon", "cloudy") %}
            mdi:weather-cloudy   
          {% elif is_state("sensor.forecast_fifth_icon", "rain") %}
            mdi:weather-pouring        
          {% elif is_state("sensor.forecast_fifth_icon", "sleet") %}
            mdi:weather-snowy-rain 
          {% elif is_state("sensor.forecast_fifth_icon", "snow") %}
            mdi:weather-snowy
          {% elif is_state("sensor.forecast_fifth_icon", "wind") %}
            mdi:weather-windy
          {% elif is_state("sensor.forecast_fifth_icon", "fog") %}
            mdi:weather-fog
          {% elif is_state("sensor.forecast_fifth_icon", "partly-cloudy-day") %}
            mdi:weather-partlycloudy
          {% elif is_state("sensor.forecast_fifth_icon", "partly-cloudy-night") %}
            mdi:weather-partlycloudy
          {% else %}
            error
          {% endif %}
      forecast_fifth_icon:
        value_template: "{{states.sensor.dark_sky_icon_5.state}}"
           
      forecast_6:
        friendly_name_template: '{{ (as_timestamp(now()) + (86400) *6) | timestamp_custom("%A", True) }}'
        value_template: >          
            {{states.sensor.dark_sky_daily_high_temperature_6.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_6.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_6.state|round(0)}}%
        icon_template: >-
          {% if is_state("sensor.forecast_sixth_icon", "clear-day") %}
            mdi:weather-sunny
          {% elif is_state("sensor.forecast_sixth_icon", "clear-night") %}
            mdi:weather-night
          {% elif is_state("sensor.forecast_sixth_icon", "cloudy") %}
            mdi:weather-cloudy   
          {% elif is_state("sensor.forecast_sixth_icon", "rain") %}
            mdi:weather-pouring        
          {% elif is_state("sensor.forecast_sixth_icon", "sleet") %}
            mdi:weather-snowy-rain  
          {% elif is_state("sensor.forecast_sixth_icon", "snow") %}
            mdi:weather-snowy
          {% elif is_state("sensor.forecast_sixth_icon", "wind") %}
            mdi:weather-windy
          {% elif is_state("sensor.forecast_sixth_icon", "fog") %}
            mdi:weather-fog
          {% elif is_state("sensor.forecast_sixth_icon", "partly-cloudy-day") %}
            mdi:weather-partlycloudy
          {% elif is_state("sensor.forecast_sixth_icon", "partly-cloudy-night") %}
            mdi:weather-partlycloudy
          {% else %}
            error
          {% endif %}
      forecast_sixth_icon:
        value_template: "{{states.sensor.dark_sky_icon_6.state}}"

      forecast_7:
        friendly_name_template: '{{ (as_timestamp(now()) + (86400) *7) | timestamp_custom("%A", True) }}'
        value_template: >
            {{states.sensor.dark_sky_daily_high_temperature_7.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_7.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_7.state|round(0)}}%
        icon_template: >-
          {% if is_state("sensor.forecast_seventh_icon", "clear-day") %}
            mdi:weather-sunny
          {% elif is_state("sensor.forecast_seventh_icon", "clear-night") %}
            mdi:weather-night
          {% elif is_state("sensor.forecast_seventh_icon", "cloudy") %}
            mdi:weather-cloudy   
          {% elif is_state("sensor.forecast_seventh_icon", "rain") %}
            mdi:weather-pouring        
          {% elif is_state("sensor.forecast_seventh_icon", "sleet") %}
            mdi:weather-snowy-rain 
          {% elif is_state("sensor.forecast_seventh_icon", "snow") %}
            mdi:weather-snowy
          {% elif is_state("sensor.forecast_seventh_icon", "wind") %}
            mdi:weather-windy
          {% elif is_state("sensor.forecast_seventh_icon", "fog") %}
            mdi:weather-fog
          {% elif is_state("sensor.forecast_seventh_icon", "partly-cloudy-day") %}
            mdi:weather-partlycloudy
          {% elif is_state("sensor.forecast_seventh_icon", "partly-cloudy-night") %}
            mdi:weather-partlycloudy
          {% else %}
            error
          {% endif %}
      forecast_seventh_icon:
        value_template: "{{states.sensor.dark_sky_icon_7.state}}"

group:
  weather_tab:
    name: Weather
    icon: mdi:weather-sunset
    view: yes
    entities:
    - group.weather_info
    - group.weather_forecast
    - group.air_quality
  weather_info:
    name: Weather
    view: no
    entities:
      - sun.sun
      - sensor.moon
      - sensor.season
      - sensor.dark_sky_summary
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_type
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_temperature
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_cloud_cover
      - sensor.dark_sky_humidity
  weather_forecast:
    name: Forecast
    view: no
    icon: mdi:sun
    entities:
      - sensor.forecast_0
      - sensor.forecast_1
      - sensor.forecast_2
      - sensor.forecast_3
      - sensor.forecast_4
      - sensor.forecast_5
      - sensor.forecast_6
      - sensor.forecast_7