camera:
  - platform: zoneminder

zoneminder:
  host: !secret zoneminder_url
  ssl: True
  username: !secret zm_username
  password: !secret zm_password

sensor:
  - platform: zoneminder
    include_archived: false

group:
  camera_front_porch:
    name: Front Porch North
    entities:
      - sensor.front_porch_status
      - sensor.front_porch_events
      - camera.front_porch
  camera_driveway:
    name: Driveway
    entities:
      - sensor.driveway_status
      - sensor.driveway_events
      - camera.driveway
  camera_corb:
    name: Corb
    entities:
      - sensor.corb_status
      - sensor.corb_events
      - camera.corb

shell_command:
  get_latest_zm_event: 'python3 /config/commands/zoneminder_events.py --fromha=True'
