camera:
  - platform: zoneminder

zoneminder:
  host: !secret zoneminder_url
  ssl: True
  username: !secret zm_username
  password: !secret zm_password

sensor:
  - platform: zoneminder
    include_archived: false

group:
  camera_frontporchnorth:
    name: Front Porch North
    view: no
    entities:
      - sensor.frontporchnorth_status
      - sensor.frontporchnorth_events
      - camera.frontporchnorth
  camera_garage:
    name: Garage
    view: no
    entities:
      - sensor.garage_status
      - sensor.garage_events
      - camera.garage
  camera_fand:
    name: Fand
    view: no
    entities:
      - sensor.fand_status
      - sensor.fand_events
      - camera.fand
  camera_corb:
    name: Corb
    view: no
    entities:
      - sensor.corb_status
      - sensor.corb_events
      - camera.corb

shell_command:
  get_latest_zm_event: 'python3 /config/commands/zoneminder_events.py --fromha=True'