camera:
  - platform: zoneminder

zoneminder:
  host: !secret zoneminder_url
  ssl: True
  username: !secret zm_username
  password: !secret zm_password

sensor:
  - platform: zoneminder
    include_archived: false

group:
  camera_front_porch:
    name: Front Porch North
    view: no
    entities:
      - sensor.front_porch_status
      - sensor.front_porch_events
      - camera.front_porch
  camera_garage:
    name: Garage
    view: no
    entities:
      - sensor.garage_status
      - sensor.garage_events
      - camera.garage
  camera_fand:
    name: Fand
    view: no
    entities:
      - sensor.fand_status
      - sensor.fand_events
      - camera.fand
  camera_corb:
    name: Corb
    view: no
    entities:
      - sensor.corb_status
      - sensor.corb_events
      - camera.corb

shell_command:
  get_latest_zm_event: 'python3 /config/commands/zoneminder_events.py --fromha=True'

automation:
  - id: front_porch_motion_notifications
    alias: Front Porch Motion
    trigger: 
      platform: state
      entity_id: sensor.front_porch_events
    condition:
      condition: template
      value_template: '{{ trigger.from_state.state < trigger.to_state.state }}'
    action:
      - service: shell_command.get_latest_zm_event
  - id: front_door_motion_notification
    alias: Front Door Motion
    trigger: 
      platform: state
      entity_id: sensor.fand_events
    action:
      - service: notify.slack
        data_template: 
          message: ':door: New motion event at Front Door (From {{ trigger.from_state.state }} to {{ trigger.to_state.state }}'
      - service: notify.notify
        data_template:
          message: "Motion has been detected at the Front Door"