zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key

sensor:
  - platform: template
    sensors:
      front_door:
        friendly_name: "Front Door"
        value_template: >-
          {%- if is_state("sensor.vision_zd2105us5_recessed_doorwindow_sensor_access_control", "23") or is_state("sensor.vision_zd2105us5_recessed_doorwindow_sensor_access_control","254") %}
            Closed
          {%- elif is_state("sensor.vision_zd2105us5_recessed_doorwindow_sensor_access_control","22") %}
            Open
          {% else %}
            Unknown
          {% endif %}  
      office_window:
        friendly_name: "Office Window"
        value_template: >-
          {%- if is_state("binary_sensor.dome_doorwindow_sensor_sensor","off") %}
              Closed
          {%- elif is_state("binary_sensor.dome_doorwindow_sensor_sensor","on") %}
            Open
          {% else %}
            Unknown
          {% endif %} 

binary_sensor:
  - platform: template
    sensors:
      garage_motion:
        friendly_name: "Garage Motion"
        device_class: motion
        value_template: "{{ is_state('sensor.zooz_zse40_4in1_sensor_burglar_2','8') }}"
      office_motion:
        friendly_name: "Office Motion"
        device_class: motion
        value_template: "{{ is_state('sensor.zooz_zse40_4_in_1_sensor_burglar','8') }}"
      master_bedroom_motion:
        friendly_name: "Master Bedroom Motion"
        device_class: motion
        value_template: "{{ is_state('sensor.master_bedroom_sensor_burglar','8') }}"