zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key

sensor:
  - platform: template
    sensors:
      front_door:
        friendly_name: "Front Door"
        value_template: >-
          {%- if is_state("sensor.vision_zd2105us5_recessed_doorwindow_sensor_access_control", "23") %}
            Closed
          {%- if is_state("sensor.vision_zd2105us5_recessed_doorwindow_sensor_access_control","22") %}
            Open
          {% else %}
            Unknown
          {% endif %}

automation:
  - id: front_door_state_change
    alias: 'Front Door Events'
    trigger:
      - platform: state
        entity_id: sensor.front_door
    action:
      - service: notify.default_group
        data_template:
          message: "Front Door is {{ trigger.to_state.state }}"
    