zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key

sensor:
  - platform: template
    sensors:
      front_door:
        friendly_name: "Front Door"
        value_template: >-
          {%- if is_state("sensor.vision_zd2105us5_recessed_doorwindow_sensor_access_control", "23") or is_state("sensor.vision_zd2105us5_recessed_doorwindow_sensor_access_control","254") %}
            Closed
          {%- elif is_state("sensor.vision_zd2105us5_recessed_doorwindow_sensor_access_control","22") %}
            Open
          {% else %}
            Unknown
          {% endif %}  
      front_door_battery: 
        friendly_name: "Siren Battery"
        value_template: '{{ states.zwave.dome_siren.attributes.battery_level }}'
        unit_of_measurement: '%'
        entity_id: zwave.dome_siren
        device_class: battery
      siren_battery: 
        friendly_name: "Front Door Battery"
        value_template: '{{ states.zwave.vision_zd2105us5_recessed_doorwindow_sensor.attributes.battery_level }}'
        unit_of_measurement: '%'
        entity_id: zwave.vision_zd2105us5_recessed_doorwindow_sensor
        device_class: battery